
# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
    - link:            "mysql:root:123Fh9IkkRwC8CF12@tcp(121.214.21.140:61111)/yjs"
#      tables:          "product"
      removePrefix:    "ys_"
      descriptionTag:  true
      noModelComment:  true
