// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// adminUserPermissionsDao is the data access object for table yjs_admin_user_permissions.
// You can define custom methods on it to extend its functionality as you wish.
type adminUserPermissionsDao struct {
	*internal.AdminUserPermissionsDao
}

var (
	// AdminUserPermissions is globally public accessible object for table yjs_admin_user_permissions operations.
	AdminUserPermissions = adminUserPermissionsDao{
		internal.NewAdminUserPermissionsDao(),
	}
)

// Fill with you ideas below.
