// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// adminUsersDao is the data access object for table yjs_admin_users.
// You can define custom methods on it to extend its functionality as you wish.
type adminUsersDao struct {
	*internal.AdminUsersDao
}

var (
	// AdminUsers is globally public accessible object for table yjs_admin_users operations.
	AdminUsers = adminUsersDao{
		internal.NewAdminUsersDao(),
	}
)

// Fill with you ideas below.
