// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// adminOperationLogDao is the data access object for table yjs_admin_operation_log.
// You can define custom methods on it to extend its functionality as you wish.
type adminOperationLogDao struct {
	*internal.AdminOperationLogDao
}

var (
	// AdminOperationLog is globally public accessible object for table yjs_admin_operation_log operations.
	AdminOperationLog = adminOperationLogDao{
		internal.NewAdminOperationLogDao(),
	}
)

// Fill with you ideas below.
