// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// adminPermissionsDao is the data access object for table yjs_admin_permissions.
// You can define custom methods on it to extend its functionality as you wish.
type adminPermissionsDao struct {
	*internal.AdminPermissionsDao
}

var (
	// AdminPermissions is globally public accessible object for table yjs_admin_permissions operations.
	AdminPermissions = adminPermissionsDao{
		internal.NewAdminPermissionsDao(),
	}
)

// Fill with you ideas below.
