// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// adminMenuDao is the data access object for table yjs_admin_menu.
// You can define custom methods on it to extend its functionality as you wish.
type adminMenuDao struct {
	*internal.AdminMenuDao
}

var (
	// AdminMenu is globally public accessible object for table yjs_admin_menu operations.
	AdminMenu = adminMenuDao{
		internal.NewAdminMenuDao(),
	}
)

// Fill with you ideas below.
