// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// adminRoleMenuDao is the data access object for table yjs_admin_role_menu.
// You can define custom methods on it to extend its functionality as you wish.
type adminRoleMenuDao struct {
	*internal.AdminRoleMenuDao
}

var (
	// AdminRoleMenu is globally public accessible object for table yjs_admin_role_menu operations.
	AdminRoleMenu = adminRoleMenuDao{
		internal.NewAdminRoleMenuDao(),
	}
)

// Fill with you ideas below.
