// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// adminConfigDao is the data access object for table yjs_admin_config.
// You can define custom methods on it to extend its functionality as you wish.
type adminConfigDao struct {
	*internal.AdminConfigDao
}

var (
	// AdminConfig is globally public accessible object for table yjs_admin_config operations.
	AdminConfig = adminConfigDao{
		internal.NewAdminConfigDao(),
	}
)

// Fill with you ideas below.
