// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// apiLogSetDao is the data access object for table yjs_api_log_set.
// You can define custom methods on it to extend its functionality as you wish.
type apiLogSetDao struct {
	*internal.ApiLogSetDao
}

var (
	// ApiLogSet is globally public accessible object for table yjs_api_log_set operations.
	ApiLogSet = apiLogSetDao{
		internal.NewApiLogSetDao(),
	}
)

// Fill with you ideas below.
