// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// blackListMacDao is the data access object for table yjs_black_list_mac.
// You can define custom methods on it to extend its functionality as you wish.
type blackListMacDao struct {
	*internal.BlackListMacDao
}

var (
	// BlackListMac is globally public accessible object for table yjs_black_list_mac operations.
	BlackListMac = blackListMacDao{
		internal.NewBlackListMacDao(),
	}
)

// Fill with you ideas below.
