// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// gameSamplesDao is the data access object for table yjs_game_samples.
// You can define custom methods on it to extend its functionality as you wish.
type gameSamplesDao struct {
	*internal.GameSamplesDao
}

var (
	// GameSamples is globally public accessible object for table yjs_game_samples operations.
	GameSamples = gameSamplesDao{
		internal.NewGameSamplesDao(),
	}
)

// Fill with you ideas below.
