// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// hostDao is the data access object for table yjs_host.
// You can define custom methods on it to extend its functionality as you wish.
type hostDao struct {
	*internal.HostDao
}

var (
	// Host is globally public accessible object for table yjs_host operations.
	Host = hostDao{
		internal.NewHostDao(),
	}
)

// Fill with you ideas below.
