// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// hostVersionDao is the data access object for table yjs_host_version.
// You can define custom methods on it to extend its functionality as you wish.
type hostVersionDao struct {
	*internal.HostVersionDao
}

var (
	// HostVersion is globally public accessible object for table yjs_host_version operations.
	HostVersion = hostVersionDao{
		internal.NewHostVersionDao(),
	}
)

// Fill with you ideas below.
