// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// machineroomDao is the data access object for table yjs_machineroom.
// You can define custom methods on it to extend its functionality as you wish.
type machineroomDao struct {
	*internal.MachineroomDao
}

var (
	// Machineroom is globally public accessible object for table yjs_machineroom operations.
	Machineroom = machineroomDao{
		internal.NewMachineroomDao(),
	}
)

// Fill with you ideas below.
