// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// migrationsDao is the data access object for table yjs_migrations.
// You can define custom methods on it to extend its functionality as you wish.
type migrationsDao struct {
	*internal.MigrationsDao
}

var (
	// Migrations is globally public accessible object for table yjs_migrations operations.
	Migrations = migrationsDao{
		internal.NewMigrationsDao(),
	}
)

// Fill with you ideas below.
