// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodesUserProductDao is the data access object for table yjs_nodes_user_product.
// You can define custom methods on it to extend its functionality as you wish.
type nodesUserProductDao struct {
	*internal.NodesUserProductDao
}

var (
	// NodesUserProduct is globally public accessible object for table yjs_nodes_user_product operations.
	NodesUserProduct = nodesUserProductDao{
		internal.NewNodesUserProductDao(),
	}
)

// Fill with you ideas below.
