// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodesProvinceDao is the data access object for table yjs_nodes_province.
// You can define custom methods on it to extend its functionality as you wish.
type nodesProvinceDao struct {
	*internal.NodesProvinceDao
}

var (
	// NodesProvince is globally public accessible object for table yjs_nodes_province operations.
	NodesProvince = nodesProvinceDao{
		internal.NewNodesProvinceDao(),
	}
)

// Fill with you ideas below.
