// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodeProvinceCopy1Dao is the data access object for table yjs_node_province_copy1.
// You can define custom methods on it to extend its functionality as you wish.
type nodeProvinceCopy1Dao struct {
	*internal.NodeProvinceCopy1Dao
}

var (
	// NodeProvinceCopy1 is globally public accessible object for table yjs_node_province_copy1 operations.
	NodeProvinceCopy1 = nodeProvinceCopy1Dao{
		internal.NewNodeProvinceCopy1Dao(),
	}
)

// Fill with you ideas below.
