// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodesMachineroomDao is the data access object for table yjs_nodes_machineroom.
// You can define custom methods on it to extend its functionality as you wish.
type nodesMachineroomDao struct {
	*internal.NodesMachineroomDao
}

var (
	// NodesMachineroom is globally public accessible object for table yjs_nodes_machineroom operations.
	NodesMachineroom = nodesMachineroomDao{
		internal.NewNodesMachineroomDao(),
	}
)

// Fill with you ideas below.
