// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodesDao is the data access object for table yjs_nodes.
// You can define custom methods on it to extend its functionality as you wish.
type nodesDao struct {
	*internal.NodesDao
}

var (
	// Nodes is globally public accessible object for table yjs_nodes operations.
	Nodes = nodesDao{
		internal.NewNodesDao(),
	}
)

// Fill with you ideas below.
