// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodesProductTypeDao is the data access object for table yjs_nodes_product_type.
// You can define custom methods on it to extend its functionality as you wish.
type nodesProductTypeDao struct {
	*internal.NodesProductTypeDao
}

var (
	// NodesProductType is globally public accessible object for table yjs_nodes_product_type operations.
	NodesProductType = nodesProductTypeDao{
		internal.NewNodesProductTypeDao(),
	}
)

// Fill with you ideas below.
