// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodeStatusReportCountDao is the data access object for table yjs_node_status_report_count.
// You can define custom methods on it to extend its functionality as you wish.
type nodeStatusReportCountDao struct {
	*internal.NodeStatusReportCountDao
}

var (
	// NodeStatusReportCount is globally public accessible object for table yjs_node_status_report_count operations.
	NodeStatusReportCount = nodeStatusReportCountDao{
		internal.NewNodeStatusReportCountDao(),
	}
)

// Fill with you ideas below.
