// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodesProductDao is the data access object for table yjs_nodes_product.
// You can define custom methods on it to extend its functionality as you wish.
type nodesProductDao struct {
	*internal.NodesProductDao
}

var (
	// NodesProduct is globally public accessible object for table yjs_nodes_product operations.
	NodesProduct = nodesProductDao{
		internal.NewNodesProductDao(),
	}
)

// Fill with you ideas below.
