// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodeProductTypeDao is the data access object for table yjs_node_product_type.
// You can define custom methods on it to extend its functionality as you wish.
type nodeProductTypeDao struct {
	*internal.NodeProductTypeDao
}

var (
	// NodeProductType is globally public accessible object for table yjs_node_product_type operations.
	NodeProductType = nodeProductTypeDao{
		internal.NewNodeProductTypeDao(),
	}
)

// Fill with you ideas below.
