// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// nodesUserSerialDao is the data access object for table yjs_nodes_user_serial.
// You can define custom methods on it to extend its functionality as you wish.
type nodesUserSerialDao struct {
	*internal.NodesUserSerialDao
}

var (
	// NodesUserSerial is globally public accessible object for table yjs_nodes_user_serial operations.
	NodesUserSerial = nodesUserSerialDao{
		internal.NewNodesUserSerialDao(),
	}
)

// Fill with you ideas below.
