// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// noticetUserDao is the data access object for table yjs_noticet_user.
// You can define custom methods on it to extend its functionality as you wish.
type noticetUserDao struct {
	*internal.NoticetUserDao
}

var (
	// NoticetUser is globally public accessible object for table yjs_noticet_user operations.
	NoticetUser = noticetUserDao{
		internal.NewNoticetUserDao(),
	}
)

// Fill with you ideas below.
