// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// preferentialStrategy1Dao is the data access object for table yjs_preferential_strategy1.
// You can define custom methods on it to extend its functionality as you wish.
type preferentialStrategy1Dao struct {
	*internal.PreferentialStrategy1Dao
}

var (
	// PreferentialStrategy1 is globally public accessible object for table yjs_preferential_strategy1 operations.
	PreferentialStrategy1 = preferentialStrategy1Dao{
		internal.NewPreferentialStrategy1Dao(),
	}
)

// Fill with you ideas below.
