// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// preferentialStrategyDao is the data access object for table yjs_preferential_strategy.
// You can define custom methods on it to extend its functionality as you wish.
type preferentialStrategyDao struct {
	*internal.PreferentialStrategyDao
}

var (
	// PreferentialStrategy is globally public accessible object for table yjs_preferential_strategy operations.
	PreferentialStrategy = preferentialStrategyDao{
		internal.NewPreferentialStrategyDao(),
	}
)

// Fill with you ideas below.
