// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// provinceDao is the data access object for table yjs_province.
// You can define custom methods on it to extend its functionality as you wish.
type provinceDao struct {
	*internal.ProvinceDao
}

var (
	// Province is globally public accessible object for table yjs_province operations.
	Province = provinceDao{
		internal.NewProvinceDao(),
	}
)

// Fill with you ideas below.
