// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// sdkBlackListIpDao is the data access object for table yjs_sdk_black_list_ip.
// You can define custom methods on it to extend its functionality as you wish.
type sdkBlackListIpDao struct {
	*internal.SdkBlackListIpDao
}

var (
	// SdkBlackListIp is globally public accessible object for table yjs_sdk_black_list_ip operations.
	SdkBlackListIp = sdkBlackListIpDao{
		internal.NewSdkBlackListIpDao(),
	}
)

// Fill with you ideas below.
