// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// sdkUserSerialDao is the data access object for table yjs_sdk_user_serial.
// You can define custom methods on it to extend its functionality as you wish.
type sdkUserSerialDao struct {
	*internal.SdkUserSerialDao
}

var (
	// SdkUserSerial is globally public accessible object for table yjs_sdk_user_serial operations.
	SdkUserSerial = sdkUserSerialDao{
		internal.NewSdkUserSerialDao(),
	}
)

// Fill with you ideas below.
