// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// sdkUserProductSettingDao is the data access object for table yjs_sdk_user_product_setting.
// You can define custom methods on it to extend its functionality as you wish.
type sdkUserProductSettingDao struct {
	*internal.SdkUserProductSettingDao
}

var (
	// SdkUserProductSetting is globally public accessible object for table yjs_sdk_user_product_setting operations.
	SdkUserProductSetting = sdkUserProductSettingDao{
		internal.NewSdkUserProductSettingDao(),
	}
)

// Fill with you ideas below.
