// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// sdkSoftwareDao is the data access object for table yjs_sdk_software.
// You can define custom methods on it to extend its functionality as you wish.
type sdkSoftwareDao struct {
	*internal.SdkSoftwareDao
}

var (
	// SdkSoftware is globally public accessible object for table yjs_sdk_software operations.
	SdkSoftware = sdkSoftwareDao{
		internal.NewSdkSoftwareDao(),
	}
)

// Fill with you ideas below.
