// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// sdkUserProduct1Dao is the data access object for table yjs_sdk_user_product1.
// You can define custom methods on it to extend its functionality as you wish.
type sdkUserProduct1Dao struct {
	*internal.SdkUserProduct1Dao
}

var (
	// SdkUserProduct1 is globally public accessible object for table yjs_sdk_user_product1 operations.
	SdkUserProduct1 = sdkUserProduct1Dao{
		internal.NewSdkUserProduct1Dao(),
	}
)

// Fill with you ideas below.
