// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// sdkRulesDao is the data access object for table yjs_sdk_rules.
// You can define custom methods on it to extend its functionality as you wish.
type sdkRulesDao struct {
	*internal.SdkRulesDao
}

var (
	// SdkRules is globally public accessible object for table yjs_sdk_rules operations.
	SdkRules = sdkRulesDao{
		internal.NewSdkRulesDao(),
	}
)

// Fill with you ideas below.
