// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// sdkUserProductLimitDao is the data access object for table yjs_sdk_user_product_limit.
// You can define custom methods on it to extend its functionality as you wish.
type sdkUserProductLimitDao struct {
	*internal.SdkUserProductLimitDao
}

var (
	// SdkUserProductLimit is globally public accessible object for table yjs_sdk_user_product_limit operations.
	SdkUserProductLimit = sdkUserProductLimitDao{
		internal.NewSdkUserProductLimitDao(),
	}
)

// Fill with you ideas below.
