// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// serialReportAvgDao is the data access object for table yjs_serial_report_avg.
// You can define custom methods on it to extend its functionality as you wish.
type serialReportAvgDao struct {
	*internal.SerialReportAvgDao
}

var (
	// SerialReportAvg is globally public accessible object for table yjs_serial_report_avg operations.
	SerialReportAvg = serialReportAvgDao{
		internal.NewSerialReportAvgDao(),
	}
)

// Fill with you ideas below.
