// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// serialReport202103Dao is the data access object for table yjs_serial_report_2021-03.
// You can define custom methods on it to extend its functionality as you wish.
type serialReport202103Dao struct {
	*internal.SerialReport202103Dao
}

var (
	// SerialReport202103 is globally public accessible object for table yjs_serial_report_2021-03 operations.
	SerialReport202103 = serialReport202103Dao{
		internal.NewSerialReport202103Dao(),
	}
)

// Fill with you ideas below.
