// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// serialReportCountDao is the data access object for table yjs_serial_report_count.
// You can define custom methods on it to extend its functionality as you wish.
type serialReportCountDao struct {
	*internal.SerialReportCountDao
}

var (
	// SerialReportCount is globally public accessible object for table yjs_serial_report_count operations.
	SerialReportCount = serialReportCountDao{
		internal.NewSerialReportCountDao(),
	}
)

// Fill with you ideas below.
