// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// serialReport202104Dao is the data access object for table yjs_serial_report_2021-04.
// You can define custom methods on it to extend its functionality as you wish.
type serialReport202104Dao struct {
	*internal.SerialReport202104Dao
}

var (
	// SerialReport202104 is globally public accessible object for table yjs_serial_report_2021-04 operations.
	SerialReport202104 = serialReport202104Dao{
		internal.NewSerialReport202104Dao(),
	}
)

// Fill with you ideas below.
