// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// smsSetDao is the data access object for table yjs_sms_set.
// You can define custom methods on it to extend its functionality as you wish.
type smsSetDao struct {
	*internal.SmsSetDao
}

var (
	// SmsSet is globally public accessible object for table yjs_sms_set operations.
	SmsSet = smsSetDao{
		internal.NewSmsSetDao(),
	}
)

// Fill with you ideas below.
