// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// softwareUpgradeDao is the data access object for table yjs_software_upgrade.
// You can define custom methods on it to extend its functionality as you wish.
type softwareUpgradeDao struct {
	*internal.SoftwareUpgradeDao
}

var (
	// SoftwareUpgrade is globally public accessible object for table yjs_software_upgrade operations.
	SoftwareUpgrade = softwareUpgradeDao{
		internal.NewSoftwareUpgradeDao(),
	}
)

// Fill with you ideas below.
