// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// softwareNodeDao is the data access object for table yjs_software_node.
// You can define custom methods on it to extend its functionality as you wish.
type softwareNodeDao struct {
	*internal.SoftwareNodeDao
}

var (
	// SoftwareNode is globally public accessible object for table yjs_software_node operations.
	SoftwareNode = softwareNodeDao{
		internal.NewSoftwareNodeDao(),
	}
)

// Fill with you ideas below.
