// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// softwarePmainDao is the data access object for table yjs_software_pmain.
// You can define custom methods on it to extend its functionality as you wish.
type softwarePmainDao struct {
	*internal.SoftwarePmainDao
}

var (
	// SoftwarePmain is globally public accessible object for table yjs_software_pmain operations.
	SoftwarePmain = softwarePmainDao{
		internal.NewSoftwarePmainDao(),
	}
)

// Fill with you ideas below.
