// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// softProvinceDao is the data access object for table yjs_soft_province.
// You can define custom methods on it to extend its functionality as you wish.
type softProvinceDao struct {
	*internal.SoftProvinceDao
}

var (
	// SoftProvince is globally public accessible object for table yjs_soft_province operations.
	SoftProvince = softProvinceDao{
		internal.NewSoftProvinceDao(),
	}
)

// Fill with you ideas below.
