// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// testDao is the data access object for table yjs_test.
// You can define custom methods on it to extend its functionality as you wish.
type testDao struct {
	*internal.TestDao
}

var (
	// Test is globally public accessible object for table yjs_test operations.
	Test = testDao{
		internal.NewTestDao(),
	}
)

// Fill with you ideas below.
