// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// userNoticeDao is the data access object for table yjs_user_notice.
// You can define custom methods on it to extend its functionality as you wish.
type userNoticeDao struct {
	*internal.UserNoticeDao
}

var (
	// UserNotice is globally public accessible object for table yjs_user_notice operations.
	UserNotice = userNoticeDao{
		internal.NewUserNoticeDao(),
	}
)

// Fill with you ideas below.
