// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// userProductConfigDao is the data access object for table yjs_user_product_config.
// You can define custom methods on it to extend its functionality as you wish.
type userProductConfigDao struct {
	*internal.UserProductConfigDao
}

var (
	// UserProductConfig is globally public accessible object for table yjs_user_product_config operations.
	UserProductConfig = userProductConfigDao{
		internal.NewUserProductConfigDao(),
	}
)

// Fill with you ideas below.
