// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// userProductConfigcommonDao is the data access object for table yjs_user_product_configcommon.
// You can define custom methods on it to extend its functionality as you wish.
type userProductConfigcommonDao struct {
	*internal.UserProductConfigcommonDao
}

var (
	// UserProductConfigcommon is globally public accessible object for table yjs_user_product_configcommon operations.
	UserProductConfigcommon = userProductConfigcommonDao{
		internal.NewUserProductConfigcommonDao(),
	}
)

// Fill with you ideas below.
