// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// userProductCountDao is the data access object for table yjs_user_product_count.
// You can define custom methods on it to extend its functionality as you wish.
type userProductCountDao struct {
	*internal.UserProductCountDao
}

var (
	// UserProductCount is globally public accessible object for table yjs_user_product_count operations.
	UserProductCount = userProductCountDao{
		internal.NewUserProductCountDao(),
	}
)

// Fill with you ideas below.
