// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// userProductKdlogDao is the data access object for table yjs_user_product_kdlog.
// You can define custom methods on it to extend its functionality as you wish.
type userProductKdlogDao struct {
	*internal.UserProductKdlogDao
}

var (
	// UserProductKdlog is globally public accessible object for table yjs_user_product_kdlog operations.
	UserProductKdlog = userProductKdlogDao{
		internal.NewUserProductKdlogDao(),
	}
)

// Fill with you ideas below.
