// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// userAccountDao is the data access object for table yjs_user_account.
// You can define custom methods on it to extend its functionality as you wish.
type userAccountDao struct {
	*internal.UserAccountDao
}

var (
	// UserAccount is globally public accessible object for table yjs_user_account operations.
	UserAccount = userAccountDao{
		internal.NewUserAccountDao(),
	}
)

// Fill with you ideas below.
