// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// userLogDao is the data access object for table yjs_user_log.
// You can define custom methods on it to extend its functionality as you wish.
type userLogDao struct {
	*internal.UserLogDao
}

var (
	// UserLog is globally public accessible object for table yjs_user_log operations.
	UserLog = userLogDao{
		internal.NewUserLogDao(),
	}
)

// Fill with you ideas below.
