// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/gogf/gf-demo-user/v2/internal/service/internal/dao/internal"
)

// userProductDao is the data access object for table yjs_user_product.
// You can define custom methods on it to extend its functionality as you wish.
type userProductDao struct {
	*internal.UserProductDao
}

var (
	// UserProduct is globally public accessible object for table yjs_user_product operations.
	UserProduct = userProductDao{
		internal.NewUserProductDao(),
	}
)

// Fill with you ideas below.
