// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminPermissions is the golang structure of table yjs_admin_permissions for DAO operations like Where/Data.
type AdminPermissions struct {
	g.Meta     `orm:"table:yjs_admin_permissions, do:true"`
	Id         interface{} //
	Name       interface{} //
	Slug       interface{} //
	HttpMethod interface{} //
	HttpPath   interface{} //
	CreatedAt  *gtime.Time //
	UpdatedAt  *gtime.Time //
}
