// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMenu is the golang structure of table yjs_admin_menu for DAO operations like Where/Data.
type AdminMenu struct {
	g.Meta    `orm:"table:yjs_admin_menu, do:true"`
	Id        interface{} //
	ParentId  interface{} //
	Order     interface{} //
	Title     interface{} //
	Icon      interface{} //
	Uri       interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
