// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminRoles is the golang structure of table yjs_admin_roles for DAO operations like Where/Data.
type AdminRoles struct {
	g.Meta    `orm:"table:yjs_admin_roles, do:true"`
	Id        interface{} //
	Name      interface{} //
	Slug      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
