// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminConfig is the golang structure of table yjs_admin_config for DAO operations like Where/Data.
type AdminConfig struct {
	g.Meta      `orm:"table:yjs_admin_config, do:true"`
	Id          interface{} //
	Name        interface{} //
	Value       interface{} //
	Description interface{} //
	CreatedAt   *gtime.Time //
	UpdatedAt   *gtime.Time //
}
