// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminRolePermissions is the golang structure of table yjs_admin_role_permissions for DAO operations like Where/Data.
type AdminRolePermissions struct {
	g.Meta       `orm:"table:yjs_admin_role_permissions, do:true"`
	RoleId       interface{} //
	PermissionId interface{} //
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
}
