// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminUsers is the golang structure of table yjs_admin_users for DAO operations like Where/Data.
type AdminUsers struct {
	g.Meta        `orm:"table:yjs_admin_users, do:true"`
	Id            interface{} //
	Username      interface{} //
	Password      interface{} //
	Name          interface{} //
	Avatar        interface{} //
	RememberToken interface{} //
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
