// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminOperationLog is the golang structure of table yjs_admin_operation_log for DAO operations like Where/Data.
type AdminOperationLog struct {
	g.Meta    `orm:"table:yjs_admin_operation_log, do:true"`
	Id        interface{} //
	UserId    interface{} //
	Path      interface{} //
	Method    interface{} //
	Ip        interface{} //
	Input     interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
