// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FailedJobs is the golang structure of table yjs_failed_jobs for DAO operations like Where/Data.
type FailedJobs struct {
	g.Meta     `orm:"table:yjs_failed_jobs, do:true"`
	Id         interface{} //
	Connection interface{} //
	Queue      interface{} //
	Payload    interface{} //
	Exception  interface{} //
	FailedAt   *gtime.Time //
}
