// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure of table yjs_file for DAO operations like Where/Data.
type File struct {
	g.Meta    `orm:"table:yjs_file, do:true"`
	Id        interface{} //
	FileName  interface{} // 文件名
	FileSize  interface{} // 文件大小
	FileExt   interface{} // 文件格式
	FilePath  interface{} // 文件所在的文件夹
	FileMd5   interface{} //
	UpdatedAt *gtime.Time //
	CreatedAt *gtime.Time //
	FileUrl   interface{} // url
}
