// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// GameSamples is the golang structure of table yjs_game_samples for DAO operations like Where/Data.
type GameSamples struct {
	g.Meta    `orm:"table:yjs_game_samples, do:true"`
	Id        interface{} //
	Name      interface{} //
	Samples   interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
