// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// HostVersion is the golang structure of table yjs_host_version for DAO operations like Where/Data.
type HostVersion struct {
	g.Meta    `orm:"table:yjs_host_version, do:true"`
	Id        interface{} //
	HostId    interface{} //
	HostIdMd5 interface{} //
	Version   interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
