// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Host is the golang structure of table yjs_host for DAO operations like Where/Data.
type Host struct {
	g.Meta        `orm:"table:yjs_host, do:true"`
	Id            interface{} //
	UserId        interface{} // 用户id
	HostName      interface{} // 主机名称
	HostBegindate interface{} // 上架时间
	HostClass     interface{} //
	HostEnddate   interface{} // 客户到期时间
	Ip            interface{} // ip数量
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
	HostId        interface{} // 主机id
}
