// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Machineroom is the golang structure of table yjs_machineroom for DAO operations like Where/Data.
type Machineroom struct {
	g.Meta    `orm:"table:yjs_machineroom, do:true"`
	Id        interface{} //
	Name      interface{} // 机房名称
	Ip        interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
