// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Migrations is the golang structure of table yjs_migrations for DAO operations like Where/Data.
type Migrations struct {
	g.Meta    `orm:"table:yjs_migrations, do:true"`
	Id        interface{} //
	Migration interface{} //
	Batch     interface{} //
}
