// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Nodes is the golang structure of table yjs_nodes for DAO operations like Where/Data.
type Nodes struct {
	g.Meta           `orm:"table:yjs_nodes, do:true"`
	Id               interface{} //
	Name             interface{} // 节点名称
	NodeType         interface{} // 1防御网关。2 安全网关
	Type             interface{} // 类型 1是共享 2是独立
	Status           interface{} // 1是启用 2是不启用
	Port             interface{} // 端口号
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
	State            interface{} // 是否启用 1正常2禁用3离线
	UserSerialId     interface{} // 分配的序列号id，可为空
	DistributionType interface{} // 1手动分配，2自动分配
	NodeVersion      interface{} // 节点版本
	DistType         interface{} // 分配类型 1、实例ID，2、序列号
	Timer            interface{} // 运行时间
	NsThreshold      interface{} // 次数
	UploadTimer      interface{} // 上报时间
	Area             interface{} // 地区配置
	AreaSafe         interface{} // 地区配置-用于匹配安全网关
	AreaLine         interface{} // 专线ip-地址
	IpLine           interface{} // 专线IP
}
