// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Node is the golang structure of table yjs_node for DAO operations like Where/Data.
type Node struct {
	g.Meta           `orm:"table:yjs_node, do:true"`
	Id               interface{} //
	HostId           interface{} // 主机id
	Name             interface{} // 节点名称
	Type             interface{} // 类型 1是共享2是独立3机房
	NodeType         interface{} // 节点类型 1防御网关。2 安全网关
	State            interface{} // 1是正常 3是离线
	OnOff            interface{} // -1是未启动，1是启动 2是关闭
	Port             interface{} // 端口号
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
	SourceType       interface{} // 节点对应来源，1云加速节点，2游戏盾sdk节点
	UserSerialId     interface{} // 分配的序列号id，可为空
	DistributionType interface{} // 1手动分配，2自动分配
	RelaxId          interface{} // 关联id
	NodeVersion      interface{} // 节点版本
	Timer            interface{} // 运行时间
	NsThreshold      interface{} // 次数
	UploadTimer      interface{} // 上报时间
	Area             interface{} // 地区配置
	AreaSafe         interface{} // 地区配置-用于匹配安全网关
	AreaLine         interface{} // 专线ip-地址
	IpLine           interface{} // 专线IP
}
