// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// NodeProductType is the golang structure of table yjs_node_product_type for DAO operations like Where/Data.
type NodeProductType struct {
	g.Meta        `orm:"table:yjs_node_product_type, do:true"`
	Id            interface{} //
	NodeId        interface{} // 节点id
	ProductTypeId interface{} // 套餐类型  'product_type'    => [          '1'=>"基础版",          '2'=>"稳定版",          '3'=>"专业版",          '4'=>"高级版",          '5'=>"定制版",      ],
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
