// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// NodesIp is the golang structure of table yjs_nodes_ip for DAO operations like Where/Data.
type NodesIp struct {
	g.Meta    `orm:"table:yjs_nodes_ip, do:true"`
	Id        interface{} //
	NodeId    interface{} // 节点id
	Ip        interface{} //
	Type      interface{} // 1是主ip
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	AreaSafe  interface{} // 地区配置-用于匹配安全网关
}
