// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// NodesProvince is the golang structure of table yjs_nodes_province for DAO operations like Where/Data.
type NodesProvince struct {
	g.Meta       `orm:"table:yjs_nodes_province, do:true"`
	Id           interface{} //
	NodeId       interface{} // 节点id
	ProvinceType interface{} // 1、省级配置，2、市级配置
	Line         interface{} // 线路1电信2联通3移动
	Area         interface{} // 地区配置信息
	SerialList   interface{} // 序列号列表
	SetType      interface{} // 1允许 2限制
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
}
