// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// NodesMachineroom is the golang structure of table yjs_nodes_machineroom for DAO operations like Where/Data.
type NodesMachineroom struct {
	g.Meta        `orm:"table:yjs_nodes_machineroom, do:true"`
	Id            interface{} //
	NodeId        interface{} // 节点id
	MachineroomId interface{} // 机房id
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
