// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// NoticetUser is the golang structure of table yjs_noticet_user for DAO operations like Where/Data.
type NoticetUser struct {
	g.Meta    `orm:"table:yjs_noticet_user, do:true"`
	Id        interface{} //
	UserId    interface{} // 用户id
	NoticetId interface{} // 公告id
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
