// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Noticet is the golang structure of table yjs_noticet for DAO operations like Where/Data.
type Noticet struct {
	g.Meta        `orm:"table:yjs_noticet, do:true"`
	Id            interface{} //
	Type          interface{} // 1是公告，2是更新日志
	Title         interface{} // 标题
	Content       interface{} // 内容
	AdminId       interface{} // 发布人ID
	AdminSurename interface{} // 发布人姓名
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
