// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PreferentialStrategy1 is the golang structure of table yjs_preferential_strategy1 for DAO operations like Where/Data.
type PreferentialStrategy1 struct {
	g.Meta            `orm:"table:yjs_preferential_strategy1, do:true"`
	Id                interface{} //
	Type              interface{} // 类型 1 购买 2 续费
	Operator          interface{} // 操作人
	PreferentialHalf  interface{} // 半年折扣
	PreferentialOne   interface{} // 一年折扣
	PreferentialTwo   interface{} // 两年折扣
	PreferentialThree interface{} // 三年折扣
	CreatedAt         *gtime.Time //
	UpdatedAt         *gtime.Time //
}
