// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure of table yjs_product for DAO operations like Where/Data.
type Product struct {
	g.Meta              `orm:"table:yjs_product, do:true"`
	Id                  interface{} //
	Name                interface{} // 产品名称
	ProductType         interface{} // 产品类型 1免费，2是普通，3是定制
	Money               interface{} // 产品金额
	Month               interface{} // 产品有效期
	Remark              interface{} // 产品备注
	Status              interface{} // 产品状态 1开启 0关闭
	Sort                interface{} // 排序
	AvailablePoints     interface{} // 可用点数
	AvaliableFrequency  interface{} // 可用封装次数
	CreatedAt           *gtime.Time //
	UpdatedAt           *gtime.Time //
	SharedNodesNum      interface{} // 共享节点数
	IndependentNodesNum interface{} // 独立节点数
	IsSdk               interface{} // 是否开启sdk功能，1开启，0关闭
}
