// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Province is the golang structure of table yjs_province for DAO operations like Where/Data.
type Province struct {
	g.Meta       `orm:"table:yjs_province, do:true"`
	Id           interface{} // 主键自增
	Pid          interface{} // 父类id
	DistrictName interface{} // 城市的名字
	Type         interface{} // 城市的类型，0是国，1是省，2是市，3是区
	Hierarchy    interface{} // 地区所处的层级
	DistrictSqe  interface{} // 层级序列
	Partition    interface{} // 分区，省有效 0其他 1东北 2华东 3华北 4华中 5华南 6西南 7西北
}
