// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Recommend is the golang structure of table yjs_recommend for DAO operations like Where/Data.
type Recommend struct {
	g.Meta        `orm:"table:yjs_recommend, do:true"`
	Id            interface{} //
	AdminId       interface{} // 发布人ID
	AdminSurename interface{} // 发布人姓名
	Title         interface{} // 图片提示
	Img           interface{} // 图片路径
	Url           interface{} // 图片链接路径
	Sort          interface{} // 排序
	CreatedAt     *gtime.Time // 创建时间
	UpdatedAt     *gtime.Time // 更新时间
	OnOff         interface{} // 是否开启 1打开2关闭
}
