// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Sdk is the golang structure of table yjs_sdk for DAO operations like Where/Data.
type Sdk struct {
	g.Meta    `orm:"table:yjs_sdk, do:true"`
	Id        interface{} //
	UserId    interface{} // 用户id
	Number    interface{} // 用户序列号
	Key       interface{} // 秘钥
	Status    interface{} // 1启用，2禁用
	Remark    interface{} // 备注
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
