// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkBlackListIp is the golang structure of table yjs_sdk_black_list_ip for DAO operations like Where/Data.
type SdkBlackListIp struct {
	g.Meta        `orm:"table:yjs_sdk_black_list_ip, do:true"`
	Id            interface{} //
	Ip            interface{} //
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
	UserProductId interface{} //
}
