// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkProduct is the golang structure of table yjs_sdk_product for DAO operations like Where/Data.
type SdkProduct struct {
	g.Meta              `orm:"table:yjs_sdk_product, do:true"`
	Id                  interface{} //
	Name                interface{} // 产品名称
	Amount              interface{} // 产品金额（月付）
	QuarterlyAmount     interface{} // 季付金额
	SemiAnnualAmount    interface{} // 半年付金额
	AnnualAmount        interface{} // 年付金额
	SharedNodesNum      interface{} // 共享节点数
	IndependentNodesNum interface{} // 独立节点数
	ForwardingRulesNum  interface{} // 转发规则数
	Ddos                interface{} // DDoS防御
	Cc                  interface{} // CC攻击防御
	SourceServersNum    interface{} // 源服务器数
	ConnectionNumber    interface{} // 连接数
	Bandwidth           interface{} // 业务带宽
	DailyActivate       interface{} // 日活终端
	Sort                interface{} // 排序
	Status              interface{} // 是否启用 1启用2不启用
	Remark              interface{} // 备注
	CreatedAt           *gtime.Time //
	UpdatedAt           *gtime.Time //
	DeletedAt           *gtime.Time //
	GameNum             interface{} // 游戏授权数
}
