// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkUserSerial is the golang structure of table yjs_sdk_user_serial for DAO operations like Where/Data.
type SdkUserSerial struct {
	g.Meta            `orm:"table:yjs_sdk_user_serial, do:true"`
	Id                interface{} // 客户类型
	UserId            interface{} // 用户id
	Number            interface{} // 用户序列号
	Guid              interface{} //
	Remark            interface{} // 序列号名称
	SdkUserProductId  interface{} // 用户产品id
	ProductId         interface{} // 产品id
	SdkKey            interface{} // 秘钥
	OnOff             interface{} // 1是启用2是关闭
	Status            interface{} // 状态 1正常 2关闭 -1 未使用
	SourceType        interface{} // 客户类型 1云加速 2游戏盾
	CreatedAt         *gtime.Time //
	UpdatedAt         *gtime.Time //
	DeletedAt         *gtime.Time //
	ClientLimit       interface{} // 客户端最大连接数
	NodeLimit         interface{} // 节点下发数量限制
	RunningTime       interface{} // 运行时间
	MaxConnect        interface{} // 一定时间内最大连接数
	ShieldTime        interface{} // 屏蔽时间
	AllRunningTime    interface{} // 总包-运行时间
	AllAllowPackage   interface{} // 总包-允许的总包数量
	AllShieldTime     interface{} // 总包-屏蔽时间
	BigRunningTime    interface{} // 大包-运行时间
	BigAllowPackage   interface{} // 大包-允许的大包数量
	BigShieldTime     interface{} // 大包-屏蔽时间
	PackageStatus     interface{} // 包-开关
	ClientLimitStatus interface{} // 客户端最大连接数开关
	SdkLimitStatus    interface{} // SDK连接数开关
}
