// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkRules is the golang structure of table yjs_sdk_rules for DAO operations like Where/Data.
type SdkRules struct {
	g.Meta        `orm:"table:yjs_sdk_rules, do:true"`
	Id            interface{} //
	UserProductId interface{} // 用户产品id
	Type          interface{} // 类型 1 PC端  2 移动端
	CustomIp      interface{} // 客户连接ip
	Port          interface{} // 转发端口
	SourceIp      interface{} // 源站ip
	Status        interface{} // 是否启用
	CreatedAt     *gtime.Time // 创建时间
	UpdatedAt     *gtime.Time //
	DeletedAt     *gtime.Time //
	PortInterval  interface{} // 步长
	PortType      interface{} // 端口类型1单一端口，2多端口（标识0-100样式）
	PortLimit     interface{} // 端口限制个数
	GetIpWay      interface{} // 获取真实ip方式：1不需要，2通过代理，3通过连接
	UserSerialId  interface{} // 用户序列号id
	CustomPort    interface{} // 客户端监听端口
}
