// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SerialReportAvg is the golang structure of table yjs_serial_report_avg for DAO operations like Where/Data.
type SerialReportAvg struct {
	g.Meta             `orm:"table:yjs_serial_report_avg, do:true"`
	Id                 interface{} //
	ProductNum         interface{} //
	ServerIp           interface{} //
	ConnectionsAvg     interface{} //
	ConnectionsMax     interface{} //
	ConnectionsMin     interface{} //
	UpLinkAvg          interface{} //
	UpLinkMax          interface{} //
	UpLinkMin          interface{} //
	DownLinkAvg        interface{} //
	DownLinkMax        interface{} //
	DownLinkMin        interface{} //
	AvgDate            *gtime.Time //
	Type               interface{} // 1-1天 2-7天 3-30天
	CreatedAt          *gtime.Time //
	UpdatedAt          *gtime.Time //
	SdkProductSerialId interface{} // sdk_user_product_id 或 user_serial_id
	ClassType          interface{} // 统计类型 1-产品 2-子序列号
}
