// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SmsSet is the golang structure of table yjs_sms_set for DAO operations like Where/Data.
type SmsSet struct {
	g.Meta    `orm:"table:yjs_sms_set, do:true"`
	Id        interface{} //
	Type      interface{} //
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
