// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Software is the golang structure of table yjs_software for DAO operations like Where/Data.
type Software struct {
	g.Meta    `orm:"table:yjs_software, do:true"`
	Id        interface{} //
	FileId    interface{} // 对应上传文件id
	FilePath  interface{} //
	Name      interface{} // 软件名称
	Version   interface{} // 版本号
	Remark    interface{} // 备注
	Sort      interface{} // 排序
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
	Type      interface{} // 1是客户端，2是服务的，3是合集
}
