// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SoftwarePmain is the golang structure of table yjs_software_pmain for DAO operations like Where/Data.
type SoftwarePmain struct {
	g.Meta                 `orm:"table:yjs_software_pmain, do:true"`
	Id                     interface{} //
	FileId                 interface{} // 对应上传文件id
	FilePath               interface{} //
	ProductType            interface{} // 序列号类型 1免费 2普通 3定制
	Name                   interface{} // 软件名称
	Version                interface{} // 版本号
	Remark                 interface{} // 备注
	Sort                   interface{} // 排序
	OperatingSystemVersion interface{} // 操作系统版本
	OperatingSystemNum     interface{} // 操作系统位数
	CreatedAt              *gtime.Time //
	UpdatedAt              *gtime.Time //
}
