// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Test is the golang structure of table yjs_test for DAO operations like Where/Data.
type Test struct {
	g.Meta `orm:"table:yjs_test, do:true"`
	Id     interface{} //
	Name   interface{} //
	Test   interface{} //
}
