// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserProductKdlog is the golang structure of table yjs_user_product_kdlog for DAO operations like Where/Data.
type UserProductKdlog struct {
	g.Meta           `orm:"table:yjs_user_product_kdlog, do:true"`
	Id               interface{} //
	UserId           interface{} //
	UserProductId    interface{} // 产品id
	Type             interface{} // 1,是运行扣点，2是封装扣点
	UserSerialNumber interface{} // 用户key值
	OldData          interface{} // 老数据
	NewData          interface{} // 新数据
	Mac              interface{} //
	Ip               interface{} //
	UpdatedAt        *gtime.Time //
	CreatedAt        *gtime.Time //
}
