// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserSerial is the golang structure of table yjs_user_serial for DAO operations like Where/Data.
type UserSerial struct {
	g.Meta           `orm:"table:yjs_user_serial, do:true"`
	Id               interface{} // 客户类型
	Lip              interface{} // 每一个序列号对应一个lip
	Port             interface{} // 端口号
	UserId           interface{} // 用户id
	Number           interface{} // 用户序列号
	Remark           interface{} // 序列号名称
	ProductType      interface{} // 序列号类型 1免费 2普通 3定制
	OnOff            interface{} // 1是启用2是关闭
	CreatedAt        *gtime.Time //
	UpdatedAt        *gtime.Time //
	Status           interface{} // 状态 1正常 2关闭 -1 未使用
	LinkType         interface{} // 1是源站，2是节点
	CustomStatus     interface{} // 自定义转发ip,1正常，2关闭
	CountUpLink      interface{} // 统计数据
	CountDownLink    interface{} // 统计数据
	CountConnections interface{} // 统计数据
	CountAt          *gtime.Time // 统计数据时间
	DeletedAt        *gtime.Time //
	SourceType       interface{} // 客户类型 1云加速 2游戏盾
}
