// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserProductDown is the golang structure of table yjs_user_product_down for DAO operations like Where/Data.
type UserProductDown struct {
	g.Meta      `orm:"table:yjs_user_product_down, do:true"`
	Id          interface{} //
	ProductType interface{} // 原版本
	DowngradeId interface{} // 降级版本
	Serial      interface{} // 序列号
	UserName    interface{} // 用户名
	UserId      interface{} // 用户id
	SellId      interface{} // 销售id
	DownAt      *gtime.Time // 降级时间
	StartAt     *gtime.Time // 开始时间
	EndAt       *gtime.Time // 到期时间
	CreatedAt   *gtime.Time // 创建时间
	UpdatedAt   *gtime.Time //
	DeletedAt   *gtime.Time //
}
