// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserProductUpdatelog is the golang structure of table yjs_user_product_updatelog for DAO operations like Where/Data.
type UserProductUpdatelog struct {
	g.Meta        `orm:"table:yjs_user_product_updatelog, do:true"`
	Id            interface{} //
	UserId        interface{} // 用户id
	UserAccountId interface{} // 账单id
	UserProductId interface{} // 用户产品id
	UserSerialId  interface{} // 用户序列号表id
	Type          interface{} // 1是续费，2是升级,3是购买
	OldData       interface{} // 旧数据
	NewData       interface{} // 新数据
	Money         interface{} // 操作价格
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
