// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserProductLimit is the golang structure of table yjs_user_product_limit for DAO operations like Where/Data.
type UserProductLimit struct {
	g.Meta        `orm:"table:yjs_user_product_limit, do:true"`
	Id            interface{} //
	UserProductId interface{} // 产品id
	ServerId      interface{} // 服务器id
	IsOpen        interface{} // 状态
	RunningTime   interface{} // 运行时间
	MaxConnect    interface{} // 一定时间内最大连接数
	ShieldTime    interface{} // 屏蔽时间
	CreatedAt     *gtime.Time //
	UpdatedAt     *gtime.Time //
}
