// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserNotice is the golang structure of table yjs_user_notice for DAO operations like Where/Data.
type UserNotice struct {
	g.Meta    `orm:"table:yjs_user_notice, do:true"`
	Id        interface{} // 记录ID
	UserId    interface{} // 消息收件人
	Content   interface{} // 消息内容
	State     interface{} // 状态:1为已读,2为未读,默认为2
	CreatedAt *gtime.Time //
	UpdatedAt *gtime.Time //
}
