// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// UserAccount is the golang structure of table yjs_user_account for DAO operations like Where/Data.
type UserAccount struct {
	g.Meta            `orm:"table:yjs_user_account, do:true"`
	Id                interface{} // 账单ID
	UserId            interface{} // 用户ID
	UserProductId     interface{} // 用户产品id
	ProductId         interface{} // 产品id
	AccountStyle      interface{} // 操作方式 1进账 2出账
	AccountType       interface{} // 1.用户充值，2.产品购买，3.产品续费
	AccountMoney      interface{} // 操作金额
	AccountIncometime interface{} // 入款时间
	AccountStatus     interface{} // 审核状态 -1待审核 1通过 2不通过 3审核中
	Content           interface{} // 备注说明
	Oldmoney          interface{} // 用户操作之前的余额
	Nowmoney          interface{} // 用户操作之后的余额
	NumberType        interface{} // 交易流水号的类型 （支付宝，微信，银行，其他等）
	Number            interface{} // 交易流水号
	CashNumber        interface{} // 代金券编码
	CashMoney         interface{} // 代金券使用金额
	CreatedAt         *gtime.Time //
	UpdatedAt         *gtime.Time //
	Status            interface{} // 入账状态 -1是未开始， 1是成功，2是失败
	Input             interface{} // 详情
	Month             interface{} // 续费月份
	UpgradeProductId  interface{} // 升级产品id
	OldData           interface{} // 旧数据
	IsAuto            interface{} // 是否自动生成 0->否 1->是
	StrategyMoney     interface{} // 折扣
}
