// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminConfig is the golang structure for table admin_config.
type AdminConfig struct {
	Id          uint        `json:"id"          ` //
	Name        string      `json:"name"        ` //
	Value       string      `json:"value"       ` //
	Description string      `json:"description" ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
