// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminRolePermissions is the golang structure for table admin_role_permissions.
type AdminRolePermissions struct {
	RoleId       int         `json:"roleId"       ` //
	PermissionId int         `json:"permissionId" ` //
	CreatedAt    *gtime.Time `json:"createdAt"    ` //
	UpdatedAt    *gtime.Time `json:"updatedAt"    ` //
}
