// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminRoles is the golang structure for table admin_roles.
type AdminRoles struct {
	Id        uint        `json:"id"        ` //
	Name      string      `json:"name"      ` //
	Slug      string      `json:"slug"      ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
