// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminUsers is the golang structure for table admin_users.
type AdminUsers struct {
	Id            uint        `json:"id"            ` //
	Username      string      `json:"username"      ` //
	Password      string      `json:"password"      ` //
	Name          string      `json:"name"          ` //
	Avatar        string      `json:"avatar"        ` //
	RememberToken string      `json:"rememberToken" ` //
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
}
