// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminPermissions is the golang structure for table admin_permissions.
type AdminPermissions struct {
	Id         uint        `json:"id"         ` //
	Name       string      `json:"name"       ` //
	Slug       string      `json:"slug"       ` //
	HttpMethod string      `json:"httpMethod" ` //
	HttpPath   string      `json:"httpPath"   ` //
	CreatedAt  *gtime.Time `json:"createdAt"  ` //
	UpdatedAt  *gtime.Time `json:"updatedAt"  ` //
}
