// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminUserPermissions is the golang structure for table admin_user_permissions.
type AdminUserPermissions struct {
	UserId       int         `json:"userId"       ` //
	PermissionId int         `json:"permissionId" ` //
	CreatedAt    *gtime.Time `json:"createdAt"    ` //
	UpdatedAt    *gtime.Time `json:"updatedAt"    ` //
}
