// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminMenu is the golang structure for table admin_menu.
type AdminMenu struct {
	Id        uint        `json:"id"        ` //
	ParentId  int         `json:"parentId"  ` //
	Order     int         `json:"order"     ` //
	Title     string      `json:"title"     ` //
	Icon      string      `json:"icon"      ` //
	Uri       string      `json:"uri"       ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
