// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminOperationLog is the golang structure for table admin_operation_log.
type AdminOperationLog struct {
	Id        uint        `json:"id"        ` //
	UserId    int         `json:"userId"    ` //
	Path      string      `json:"path"      ` //
	Method    string      `json:"method"    ` //
	Ip        string      `json:"ip"        ` //
	Input     string      `json:"input"     ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
