// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// AdminRoleMenu is the golang structure for table admin_role_menu.
type AdminRoleMenu struct {
	RoleId    int         `json:"roleId"    ` //
	MenuId    int         `json:"menuId"    ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
