// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ApiLogSet is the golang structure for table api_log_set.
type ApiLogSet struct {
	Id        uint        `json:"id"        ` //
	OnOff     int         `json:"onOff"     ` // 是否记录结果，1是，2否
	ApiType   string      `json:"apiType"   ` // 需要记录的api协议
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
