// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// File is the golang structure for table file.
type File struct {
	Id        uint        `json:"id"        ` //
	FileName  string      `json:"fileName"  ` // 文件名
	FileSize  string      `json:"fileSize"  ` // 文件大小
	FileExt   string      `json:"fileExt"   ` // 文件格式
	FilePath  string      `json:"filePath"  ` // 文件所在的文件夹
	FileMd5   string      `json:"fileMd5"   ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	FileUrl   string      `json:"fileUrl"   ` // url
}
