// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// GameSamples is the golang structure for table game_samples.
type GameSamples struct {
	Id        uint        `json:"id"        ` //
	Name      string      `json:"name"      ` //
	Samples   string      `json:"samples"   ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
