// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Host is the golang structure for table host.
type Host struct {
	Id            int         `json:"id"            ` //
	UserId        int         `json:"userId"        ` // 用户id
	HostName      string      `json:"hostName"      ` // 主机名称
	HostBegindate int         `json:"hostBegindate" ` // 上架时间
	HostClass     int         `json:"hostClass"     ` //
	HostEnddate   int         `json:"hostEnddate"   ` // 客户到期时间
	Ip            string      `json:"ip"            ` // ip数量
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
	HostId        int         `json:"hostId"        ` // 主机id
}
