// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// HostVersion is the golang structure for table host_version.
type HostVersion struct {
	Id        uint        `json:"id"        ` //
	HostId    int         `json:"hostId"    ` //
	HostIdMd5 string      `json:"hostIdMd5" ` //
	Version   string      `json:"version"   ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
