// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

// Ips is the golang structure for table ips.
type Ips struct {
	Start    uint   `json:"start"    ` //
	End      uint   `json:"end"      ` //
	Startip  string `json:"startip"  ` //
	Endip    string `json:"endip"    ` //
	Country  string `json:"country"  ` //
	Province string `json:"province" ` //
	City     string `json:"city"     ` //
	Operator string `json:"operator" ` //
	Zipcode  uint   `json:"zipcode"  ` //
	Areacode uint   `json:"areacode" ` //
}
