// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// LoginLog is the golang structure for table login_log.
type LoginLog struct {
	Id        uint        `json:"id"        ` //
	Username  string      `json:"username"  ` //
	UserId    int         `json:"userId"    ` //
	LoginType int         `json:"loginType" ` // 登录方式，1云加速，2官网
	LoginIp   string      `json:"loginIp"   ` // 登录ip
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
