// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Machineroom is the golang structure for table machineroom.
type Machineroom struct {
	Id        int         `json:"id"        ` //
	Name      string      `json:"name"      ` // 机房名称
	Ip        string      `json:"ip"        ` //
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
