// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// NodeStatusReportCount is the golang structure for table node_status_report_count.
type NodeStatusReportCount struct {
	Id          uint        `json:"id"          ` //
	NodeId      int         `json:"nodeId"      ` // 节点id
	SourceType  int         `json:"sourceType"  ` // 数据来源类型，1云加速节点，2游戏盾节点
	Connections int         `json:"connections" ` // 并发数
	BytesSent   int         `json:"bytesSent"   ` // 发送字节数
	BytesRecv   int         `json:"bytesRecv"   ` // 接收字节数
	PacketsSent int         `json:"packetsSent" ` // 发送数据包数量
	PacketsRecv int         `json:"packetsRecv" ` // 接收数据包数量
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
