// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// NodesProvince is the golang structure for table nodes_province.
type NodesProvince struct {
	Id           uint        `json:"id"           ` //
	NodeId       int         `json:"nodeId"       ` // 节点id
	ProvinceType int         `json:"provinceType" ` // 1、省级配置，2、市级配置
	Line         string      `json:"line"         ` // 线路1电信2联通3移动
	Area         string      `json:"area"         ` // 地区配置信息
	SerialList   string      `json:"serialList"   ` // 序列号列表
	SetType      int         `json:"setType"      ` // 1允许 2限制
	CreatedAt    *gtime.Time `json:"createdAt"    ` //
	UpdatedAt    *gtime.Time `json:"updatedAt"    ` //
}
