// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Nodes is the golang structure for table nodes.
type Nodes struct {
	Id               int         `json:"id"               ` //
	Name             string      `json:"name"             ` // 节点名称
	NodeType         int         `json:"nodeType"         ` // 1防御网关。2 安全网关
	Type             int         `json:"type"             ` // 类型 1是共享 2是独立
	Status           int         `json:"status"           ` // 1是启用 2是不启用
	Port             int         `json:"port"             ` // 端口号
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
	State            int         `json:"state"            ` // 是否启用 1正常2禁用3离线
	UserSerialId     int         `json:"userSerialId"     ` // 分配的序列号id，可为空
	DistributionType int         `json:"distributionType" ` // 1手动分配，2自动分配
	NodeVersion      string      `json:"nodeVersion"      ` // 节点版本
	DistType         int         `json:"distType"         ` // 分配类型 1、实例ID，2、序列号
	Timer            int         `json:"timer"            ` // 运行时间
	NsThreshold      int         `json:"nsThreshold"      ` // 次数
	UploadTimer      int         `json:"uploadTimer"      ` // 上报时间
	Area             string      `json:"area"             ` // 地区配置
	AreaSafe         string      `json:"areaSafe"         ` // 地区配置-用于匹配安全网关
	AreaLine         string      `json:"areaLine"         ` // 专线ip-地址
	IpLine           string      `json:"ipLine"           ` // 专线IP
}
