// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// NodeUserserial is the golang structure for table node_userserial.
type NodeUserserial struct {
	Id               int         `json:"id"               ` //
	NodeId           int         `json:"nodeId"           ` // 节点id
	UserSerialId     int         `json:"userSerialId"     ` // 序列号id
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
	MachineId        int         `json:"machineId"        ` // 机房id
	DistributionType int         `json:"distributionType" ` // 1手动分配，2自动分配
	Type             int         `json:"type"             ` // 1共享。2 独立
	NodeType         int         `json:"nodeType"         ` // 1防御网关。2 安全网关
}
