// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Node is the golang structure for table node.
type Node struct {
	Id               int         `json:"id"               ` //
	HostId           int         `json:"hostId"           ` // 主机id
	Name             string      `json:"name"             ` // 节点名称
	Type             int         `json:"type"             ` // 类型 1是共享2是独立3机房
	NodeType         int         `json:"nodeType"         ` // 节点类型 1防御网关。2 安全网关
	State            int         `json:"state"            ` // 1是正常 3是离线
	OnOff            int         `json:"onOff"            ` // -1是未启动，1是启动 2是关闭
	Port             int         `json:"port"             ` // 端口号
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
	SourceType       int         `json:"sourceType"       ` // 节点对应来源，1云加速节点，2游戏盾sdk节点
	UserSerialId     int         `json:"userSerialId"     ` // 分配的序列号id，可为空
	DistributionType int         `json:"distributionType" ` // 1手动分配，2自动分配
	RelaxId          int         `json:"relaxId"          ` // 关联id
	NodeVersion      string      `json:"nodeVersion"      ` // 节点版本
	Timer            int         `json:"timer"            ` // 运行时间
	NsThreshold      int         `json:"nsThreshold"      ` // 次数
	UploadTimer      int         `json:"uploadTimer"      ` // 上报时间
	Area             string      `json:"area"             ` // 地区配置
	AreaSafe         string      `json:"areaSafe"         ` // 地区配置-用于匹配安全网关
	AreaLine         string      `json:"areaLine"         ` // 专线ip-地址
	IpLine           string      `json:"ipLine"           ` // 专线IP
}
