// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

// NodeProvince is the golang structure for table node_province.
type NodeProvince struct {
	Id           uint   `json:"id"           ` //
	NodeId       int    `json:"nodeId"       ` // 节点id
	Province     string `json:"province"     ` // 省份
	ProvinceType int    `json:"provinceType" ` // 1、省级配置，2、市级配置
	MachineId    string `json:"machineId"    ` // 机房id
	City         string `json:"city"         ` // 城市
	Line         string `json:"line"         ` // 线路1电信2联通3移动
	CreatedAt    string `json:"createdAt"    ` //
	UpdatedAt    string `json:"updatedAt"    ` //
	SerialList   string `json:"serialList"   ` // 序列号
	Area         string `json:"area"         ` // 省份
	SetType      int    `json:"setType"      ` // 1允许 2限制
}
