// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// NodeIp is the golang structure for table node_ip.
type NodeIp struct {
	Id        int         `json:"id"        ` //
	NodeId    int         `json:"nodeId"    ` // 节点id
	Ip        string      `json:"ip"        ` //
	Type      int         `json:"type"      ` // 1是主ip
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	AreaSafe  string      `json:"areaSafe"  ` // 地区配置-用于匹配安全网关
}
