// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// NodesUserProduct is the golang structure for table nodes_user_product.
type NodesUserProduct struct {
	Id               int         `json:"id"               ` //
	NodeId           int         `json:"nodeId"           ` // 节点id
	Ip               string      `json:"ip"               ` // 对应的ip信息
	UserProductId    int         `json:"userProductId"    ` // 用户产品id
	DistributionType int         `json:"distributionType" ` // 1手动分配，2自动分配
	Type             int         `json:"type"             ` // 1共享。2 独立
	NodeType         int         `json:"nodeType"         ` // 1防御网关。2 安全网关
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
}
