// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Noticet is the golang structure for table noticet.
type Noticet struct {
	Id            uint        `json:"id"            ` //
	Type          int         `json:"type"          ` // 1是公告，2是更新日志
	Title         string      `json:"title"         ` // 标题
	Content       string      `json:"content"       ` // 内容
	AdminId       int         `json:"adminId"       ` // 发布人ID
	AdminSurename string      `json:"adminSurename" ` // 发布人姓名
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
}
