// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Product is the golang structure for table product.
type Product struct {
	Id                  uint        `json:"id"                  ` //
	Name                string      `json:"name"                ` // 产品名称
	ProductType         int         `json:"productType"         ` // 产品类型 1免费，2是普通，3是定制
	Money               float64     `json:"money"               ` // 产品金额
	Month               int         `json:"month"               ` // 产品有效期
	Remark              string      `json:"remark"              ` // 产品备注
	Status              int         `json:"status"              ` // 产品状态 1开启 0关闭
	Sort                int         `json:"sort"                ` // 排序
	AvailablePoints     int         `json:"availablePoints"     ` // 可用点数
	AvaliableFrequency  int         `json:"avaliableFrequency"  ` // 可用封装次数
	CreatedAt           *gtime.Time `json:"createdAt"           ` //
	UpdatedAt           *gtime.Time `json:"updatedAt"           ` //
	SharedNodesNum      int         `json:"sharedNodesNum"      ` // 共享节点数
	IndependentNodesNum int         `json:"independentNodesNum" ` // 独立节点数
	IsSdk               int         `json:"isSdk"               ` // 是否开启sdk功能，1开启，0关闭
}
