// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Recommend is the golang structure for table recommend.
type Recommend struct {
	Id            uint        `json:"id"            ` //
	AdminId       int         `json:"adminId"       ` // 发布人ID
	AdminSurename string      `json:"adminSurename" ` // 发布人姓名
	Title         string      `json:"title"         ` // 图片提示
	Img           string      `json:"img"           ` // 图片路径
	Url           string      `json:"url"           ` // 图片链接路径
	Sort          int         `json:"sort"          ` // 排序
	CreatedAt     *gtime.Time `json:"createdAt"     ` // 创建时间
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` // 更新时间
	OnOff         int         `json:"onOff"         ` // 是否开启 1打开2关闭
}
