// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Sdk is the golang structure for table sdk.
type Sdk struct {
	Id        uint        `json:"id"        ` //
	UserId    int         `json:"userId"    ` // 用户id
	Number    string      `json:"number"    ` // 用户序列号
	Key       string      `json:"key"       ` // 秘钥
	Status    int         `json:"status"    ` // 1启用，2禁用
	Remark    string      `json:"remark"    ` // 备注
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
