// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkUserProductLimit is the golang structure for table sdk_user_product_limit.
type SdkUserProductLimit struct {
	Id            uint        `json:"id"            ` //
	UserProductId int         `json:"userProductId" ` // 产品id
	ServerId      int         `json:"serverId"      ` // 服务器id
	IsOpen        int         `json:"isOpen"        ` // 状态
	RunningTime   int         `json:"runningTime"   ` // 运行时间
	MaxConnect    int         `json:"maxConnect"    ` // 一定时间内最大连接数
	ShieldTime    int         `json:"shieldTime"    ` // 屏蔽时间
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
}
