// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkBlackListMac is the golang structure for table sdk_black_list_mac.
type SdkBlackListMac struct {
	Id            uint        `json:"id"            ` //
	Mac           string      `json:"mac"           ` //
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
	UserProductId int         `json:"userProductId" ` //
}
