// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkUserSerial is the golang structure for table sdk_user_serial.
type SdkUserSerial struct {
	Id                uint        `json:"id"                ` // 客户类型
	UserId            int         `json:"userId"            ` // 用户id
	Number            string      `json:"number"            ` // 用户序列号
	Guid              int         `json:"guid"              ` //
	Remark            string      `json:"remark"            ` // 序列号名称
	SdkUserProductId  int         `json:"sdkUserProductId"  ` // 用户产品id
	ProductId         int         `json:"productId"         ` // 产品id
	SdkKey            string      `json:"sdkKey"            ` // 秘钥
	OnOff             int         `json:"onOff"             ` // 1是启用2是关闭
	Status            int         `json:"status"            ` // 状态 1正常 2关闭 -1 未使用
	SourceType        int         `json:"sourceType"        ` // 客户类型 1云加速 2游戏盾
	CreatedAt         *gtime.Time `json:"createdAt"         ` //
	UpdatedAt         *gtime.Time `json:"updatedAt"         ` //
	DeletedAt         *gtime.Time `json:"deletedAt"         ` //
	ClientLimit       int         `json:"clientLimit"       ` // 客户端最大连接数
	NodeLimit         int         `json:"nodeLimit"         ` // 节点下发数量限制
	RunningTime       int         `json:"runningTime"       ` // 运行时间
	MaxConnect        int         `json:"maxConnect"        ` // 一定时间内最大连接数
	ShieldTime        int         `json:"shieldTime"        ` // 屏蔽时间
	AllRunningTime    int         `json:"allRunningTime"    ` // 总包-运行时间
	AllAllowPackage   int         `json:"allAllowPackage"   ` // 总包-允许的总包数量
	AllShieldTime     int         `json:"allShieldTime"     ` // 总包-屏蔽时间
	BigRunningTime    int         `json:"bigRunningTime"    ` // 大包-运行时间
	BigAllowPackage   int         `json:"bigAllowPackage"   ` // 大包-允许的大包数量
	BigShieldTime     int         `json:"bigShieldTime"     ` // 大包-屏蔽时间
	PackageStatus     int         `json:"packageStatus"     ` // 包-开关
	ClientLimitStatus uint        `json:"clientLimitStatus" ` // 客户端最大连接数开关
	SdkLimitStatus    uint        `json:"sdkLimitStatus"    ` // SDK连接数开关
}
