// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkUserProduct is the golang structure for table sdk_user_product.
type SdkUserProduct struct {
	Id          uint        `json:"id"          ` //
	UserId      int         `json:"userId"      ` // 用户id
	DeviceId    string      `json:"deviceId"    ` // 实例id
	Lip         string      `json:"lip"         ` // 客户连接ip
	ProductId   int         `json:"productId"   ` // 产品id
	OnOff       int         `json:"onOff"       ` // -1是未初始化，1是启用，2是关闭
	Status      int         `json:"status"      ` // 用户产品状态1正常 2关闭 -1未支付
	Name        string      `json:"name"        ` // 产品名称
	StartAt     *gtime.Time `json:"startAt"     ` // 生效日期
	EndAt       *gtime.Time `json:"endAt"       ` // 失效日期
	Bz          string      `json:"bz"          ` // 备注
	ClientLimit int         `json:"clientLimit" ` // 客户端最大连接数
	Username    string      `json:"username"    ` // sdk字段-所属用户
	Amount      float64     `json:"amount"      ` // sdk字段-金额
	TradedMode  int         `json:"tradedMode"  ` // sdk字段-交易方式
	TradedType  int         `json:"tradedType"  ` // sdk字段-交易类型
	OrderType   int         `json:"orderType"   ` // sdk字段-订单类型
	Operator    string      `json:"operator"    ` // SDK字段-操作员
	SourceType  int         `json:"sourceType"  ` // 客户来源 1云加速 2sdk
	Remarks     string      `json:"remarks"     ` // 数据中心-列表备注
	RealAmount  float64     `json:"realAmount"  ` // 数据中心-实际支付价格
	SellId      int         `json:"sellId"      ` // 销售id
	NodeLimit   int         `json:"nodeLimit"   ` // 节点下发数量限制
	DayRemark   string      `json:"dayRemark"   ` // 日常备注（数据中心使用）
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
	DeletedAt   *gtime.Time `json:"deletedAt"   ` //
}
