// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkRules is the golang structure for table sdk_rules.
type SdkRules struct {
	Id            uint        `json:"id"            ` //
	UserProductId int         `json:"userProductId" ` // 用户产品id
	Type          int         `json:"type"          ` // 类型 1 PC端  2 移动端
	CustomIp      string      `json:"customIp"      ` // 客户连接ip
	Port          string      `json:"port"          ` // 转发端口
	SourceIp      string      `json:"sourceIp"      ` // 源站ip
	Status        int         `json:"status"        ` // 是否启用
	CreatedAt     *gtime.Time `json:"createdAt"     ` // 创建时间
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
	DeletedAt     *gtime.Time `json:"deletedAt"     ` //
	PortInterval  int         `json:"portInterval"  ` // 步长
	PortType      int         `json:"portType"      ` // 端口类型1单一端口，2多端口（标识0-100样式）
	PortLimit     int         `json:"portLimit"     ` // 端口限制个数
	GetIpWay      int         `json:"getIpWay"      ` // 获取真实ip方式：1不需要，2通过代理，3通过连接
	UserSerialId  int         `json:"userSerialId"  ` // 用户序列号id
	CustomPort    string      `json:"customPort"    ` // 客户端监听端口
}
