// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkUserProductConfigcommon is the golang structure for table sdk_user_product_configcommon.
type SdkUserProductConfigcommon struct {
	Id            uint        `json:"id"            ` //
	Name          string      `json:"name"          ` // 配置名称
	UserProductId int         `json:"userProductId" ` //
	Lip           string      `json:"lip"           ` // Local IP即终端代理要监听的本地Ip
	Port          int         `json:"port"          ` // 端口号
	Guid          int         `json:"guid"          ` //
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
}
