// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkUserProduct1 is the golang structure for table sdk_user_product1.
type SdkUserProduct1 struct {
	Id                  uint        `json:"id"                  ` //
	UserId              int         `json:"userId"              ` // 用户id
	ProductId           int         `json:"productId"           ` // 产品id
	UserSerialId        int         `json:"userSerialId"        ` // 用户序列号表id
	ProductType         int         `json:"productType"         ` // 对应产品表的类型
	HostName            string      `json:"hostName"            ` // 1是服务器2是云
	HostType            int         `json:"hostType"            ` // 1是服务器2是云
	HostId              int         `json:"hostId"              ` // 产品id
	OnOff               int         `json:"onOff"               ` // -1是未初始化，1是启用，2是关闭
	Status              int         `json:"status"              ` // 用户产品状态1正常 2关闭 -1未支付
	Name                string      `json:"name"                ` // 产品名称
	AvailablePoints     int         `json:"availablePoints"     ` // 可用点数
	AvaliableFrequency  int         `json:"avaliableFrequency"  ` // 可用封装次数
	CreatedAt           *gtime.Time `json:"createdAt"           ` //
	UpdatedAt           *gtime.Time `json:"updatedAt"           ` //
	StartAt             *gtime.Time `json:"startAt"             ` // 生效日期
	EndAt               *gtime.Time `json:"endAt"               ` // 失效日期
	Bz                  string      `json:"bz"                  ` //
	ClientLimit         int         `json:"clientLimit"         ` // 客户端最大连接数
	SharedNodesNum      int         `json:"sharedNodesNum"      ` // 共享节点数
	IndependentNodesNum int         `json:"independentNodesNum" ` // 独立节点数
	CountUpLink         int         `json:"countUpLink"         ` // 统计数据
	CountDownLink       int         `json:"countDownLink"       ` // 统计数据
	CountConnections    int         `json:"countConnections"    ` // 统计数据
	CountAt             *gtime.Time `json:"countAt"             ` // 统计数据时间
	IsLogo              int         `json:"isLogo"              ` // 是否展示logo,1展示，0不展示
	Username            string      `json:"username"            ` // sdk字段-所属用户
	ProductNum          string      `json:"productNum"          ` // sdk字段-产品编号
	Amount              float64     `json:"amount"              ` // sdk字段-金额
	TradedMode          int         `json:"tradedMode"          ` // sdk字段-交易方式
	TradedType          int         `json:"tradedType"          ` // sdk字段-交易类型
	OrderType           int         `json:"orderType"           ` // sdk字段-订单类型
	DeletedAt           *gtime.Time `json:"deletedAt"           ` //
	Operator            string      `json:"operator"            ` // SDK字段
	SourceType          int         `json:"sourceType"          ` // 客户来源 1云加速 2sdk
	SdkNum              string      `json:"sdkNum"              ` // sdk_num
	Guid                int         `json:"guid"                ` // 规则改变标识
	SkinFile            int         `json:"skinFile"            ` // 客户端皮肤资源包 文件ID
	IcoImg              int         `json:"icoImg"              ` // 托盘图标 文件ID
	Remarks             string      `json:"remarks"             ` // 数据中心-列表备注
	RealAmount          float64     `json:"realAmount"          ` // 数据中心-实际支付价格
	SellId              int         `json:"sellId"              ` // 销售id
	NodeLimit           int         `json:"nodeLimit"           ` // 节点下发数量限制
	GameNum             int         `json:"gameNum"             ` // 游戏数量限制
}
