// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SdkProduct is the golang structure for table sdk_product.
type SdkProduct struct {
	Id                  uint        `json:"id"                  ` //
	Name                string      `json:"name"                ` // 产品名称
	Amount              float64     `json:"amount"              ` // 产品金额（月付）
	QuarterlyAmount     float64     `json:"quarterlyAmount"     ` // 季付金额
	SemiAnnualAmount    float64     `json:"semiAnnualAmount"    ` // 半年付金额
	AnnualAmount        float64     `json:"annualAmount"        ` // 年付金额
	SharedNodesNum      int         `json:"sharedNodesNum"      ` // 共享节点数
	IndependentNodesNum int         `json:"independentNodesNum" ` // 独立节点数
	ForwardingRulesNum  int         `json:"forwardingRulesNum"  ` // 转发规则数
	Ddos                string      `json:"ddos"                ` // DDoS防御
	Cc                  int         `json:"cc"                  ` // CC攻击防御
	SourceServersNum    string      `json:"sourceServersNum"    ` // 源服务器数
	ConnectionNumber    int         `json:"connectionNumber"    ` // 连接数
	Bandwidth           string      `json:"bandwidth"           ` // 业务带宽
	DailyActivate       int         `json:"dailyActivate"       ` // 日活终端
	Sort                int         `json:"sort"                ` // 排序
	Status              int         `json:"status"              ` // 是否启用 1启用2不启用
	Remark              string      `json:"remark"              ` // 备注
	CreatedAt           *gtime.Time `json:"createdAt"           ` //
	UpdatedAt           *gtime.Time `json:"updatedAt"           ` //
	DeletedAt           *gtime.Time `json:"deletedAt"           ` //
	GameNum             int         `json:"gameNum"             ` // 游戏授权数
}
