// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SerialReport202103 is the golang structure for table serial_report_2021-03.
type SerialReport202103 struct {
	Id          uint        `json:"id"          ` //
	Port        string      `json:"port"        ` //
	ProductNum  string      `json:"productNum"  ` //
	Connections int         `json:"connections" ` //
	UpLink      int         `json:"upLink"      ` //
	DownLink    int         `json:"downLink"    ` //
	ServerIp    string      `json:"serverIp"    ` //
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
}
