// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SerialReportAvg is the golang structure for table serial_report_avg.
type SerialReportAvg struct {
	Id                 uint        `json:"id"                 ` //
	ProductNum         string      `json:"productNum"         ` //
	ServerIp           string      `json:"serverIp"           ` //
	ConnectionsAvg     int         `json:"connectionsAvg"     ` //
	ConnectionsMax     int         `json:"connectionsMax"     ` //
	ConnectionsMin     int         `json:"connectionsMin"     ` //
	UpLinkAvg          int         `json:"upLinkAvg"          ` //
	UpLinkMax          int         `json:"upLinkMax"          ` //
	UpLinkMin          int         `json:"upLinkMin"          ` //
	DownLinkAvg        int         `json:"downLinkAvg"        ` //
	DownLinkMax        int         `json:"downLinkMax"        ` //
	DownLinkMin        int         `json:"downLinkMin"        ` //
	AvgDate            *gtime.Time `json:"avgDate"            ` //
	Type               int         `json:"type"               ` // 1-1天 2-7天 3-30天
	CreatedAt          *gtime.Time `json:"createdAt"          ` //
	UpdatedAt          *gtime.Time `json:"updatedAt"          ` //
	SdkProductSerialId int         `json:"sdkProductSerialId" ` // sdk_user_product_id 或 user_serial_id
	ClassType          int         `json:"classType"          ` // 统计类型 1-产品 2-子序列号
}
