// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SoftwareNode is the golang structure for table software_node.
type SoftwareNode struct {
	Id        int         `json:"id"        ` //
	FileId    int         `json:"fileId"    ` // 对应上传文件id
	FilePath  string      `json:"filePath"  ` //
	Name      string      `json:"name"      ` // 软件名称
	Version   string      `json:"version"   ` // 版本号
	Remark    string      `json:"remark"    ` // 备注
	Sort      int         `json:"sort"      ` // 排序
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
	Type      int         `json:"type"      ` // 1是客户端，2是服务的，3是合集
}
