// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

// Test is the golang structure for table test.
type Test struct {
	Id   uint   `json:"id"   ` //
	Name string `json:"name" ` //
	Test string `json:"test" ` //
}
