// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserNotice is the golang structure for table user_notice.
type UserNotice struct {
	Id        uint        `json:"id"        ` // 记录ID
	UserId    uint        `json:"userId"    ` // 消息收件人
	Content   string      `json:"content"   ` // 消息内容
	State     uint        `json:"state"     ` // 状态:1为已读,2为未读,默认为2
	CreatedAt *gtime.Time `json:"createdAt" ` //
	UpdatedAt *gtime.Time `json:"updatedAt" ` //
}
