// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserLog is the golang structure for table user_log.
type UserLog struct {
	Id          uint        `json:"id"          ` //
	UserName    string      `json:"userName"    ` // 用户名
	Ip          string      `json:"ip"          ` // IP
	Model       string      `json:"model"       ` // 功能模块
	ProductNum  string      `json:"productNum"  ` // 产品编号
	Type        string      `json:"type"        ` // 操作类型
	Content     string      `json:"content"     ` // 内容
	Status      int         `json:"status"      ` // 结果
	CreatedAt   *gtime.Time `json:"createdAt"   ` //
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
	SourceType  int         `json:"sourceType"  ` //
	SubUserId   int         `json:"subUserId"   ` // 子账号id
	SubUserName string      `json:"subUserName" ` // 子账号用户名
}
