// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserProductUpdatelog is the golang structure for table user_product_updatelog.
type UserProductUpdatelog struct {
	Id            uint        `json:"id"            ` //
	UserId        int         `json:"userId"        ` // 用户id
	UserAccountId int         `json:"userAccountId" ` // 账单id
	UserProductId int         `json:"userProductId" ` // 用户产品id
	UserSerialId  int         `json:"userSerialId"  ` // 用户序列号表id
	Type          int         `json:"type"          ` // 1是续费，2是升级,3是购买
	OldData       string      `json:"oldData"       ` // 旧数据
	NewData       string      `json:"newData"       ` // 新数据
	Money         float64     `json:"money"         ` // 操作价格
	CreatedAt     *gtime.Time `json:"createdAt"     ` //
	UpdatedAt     *gtime.Time `json:"updatedAt"     ` //
}
