// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserProductDown is the golang structure for table user_product_down.
type UserProductDown struct {
	Id          uint        `json:"id"          ` //
	ProductType int         `json:"productType" ` // 原版本
	DowngradeId int         `json:"downgradeId" ` // 降级版本
	Serial      string      `json:"serial"      ` // 序列号
	UserName    string      `json:"userName"    ` // 用户名
	UserId      int         `json:"userId"      ` // 用户id
	SellId      int         `json:"sellId"      ` // 销售id
	DownAt      *gtime.Time `json:"downAt"      ` // 降级时间
	StartAt     *gtime.Time `json:"startAt"     ` // 开始时间
	EndAt       *gtime.Time `json:"endAt"       ` // 到期时间
	CreatedAt   *gtime.Time `json:"createdAt"   ` // 创建时间
	UpdatedAt   *gtime.Time `json:"updatedAt"   ` //
	DeletedAt   *gtime.Time `json:"deletedAt"   ` //
}
