// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// UserProductCount is the golang structure for table user_product_count.
type UserProductCount struct {
	Id               uint        `json:"id"               ` //
	UserProductCount string      `json:"userProductCount" ` //
	YxdCount         int         `json:"yxdCount"         ` //
	YjsCount         int         `json:"yjsCount"         ` //
	CreatedAt        *gtime.Time `json:"createdAt"        ` //
	UpdatedAt        *gtime.Time `json:"updatedAt"        ` //
}
