// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// AdminRolesDao is the data access object for table yjs_admin_roles.
type AdminRolesDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns AdminRolesColumns // columns contains all the column names of Table for convenient usage.
}

// AdminRolesColumns defines and stores column names for table yjs_admin_roles.
type AdminRolesColumns struct {
	Id        string //
	Name      string //
	Slug      string //
	CreatedAt string //
	UpdatedAt string //
}

//  adminRolesColumns holds the columns for table yjs_admin_roles.
var adminRolesColumns = AdminRolesColumns{
	Id:        "id",
	Name:      "name",
	Slug:      "slug",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewAdminRolesDao creates and returns a new DAO object for table data access.
func NewAdminRolesDao() *AdminRolesDao {
	return &AdminRolesDao{
		group:   "default",
		table:   "yjs_admin_roles",
		columns: adminRolesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *AdminRolesDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *AdminRolesDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *AdminRolesDao) Columns() AdminRolesColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *AdminRolesDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *AdminRolesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *AdminRolesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
