// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ApiLogSetDao is the data access object for table yjs_api_log_set.
type ApiLogSetDao struct {
	table   string           // table is the underlying table name of the DAO.
	group   string           // group is the database configuration group name of current DAO.
	columns ApiLogSetColumns // columns contains all the column names of Table for convenient usage.
}

// ApiLogSetColumns defines and stores column names for table yjs_api_log_set.
type ApiLogSetColumns struct {
	Id        string //
	OnOff     string // 是否记录结果，1是，2否
	ApiType   string // 需要记录的api协议
	CreatedAt string //
	UpdatedAt string //
}

//  apiLogSetColumns holds the columns for table yjs_api_log_set.
var apiLogSetColumns = ApiLogSetColumns{
	Id:        "id",
	OnOff:     "on_off",
	ApiType:   "api_type",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewApiLogSetDao creates and returns a new DAO object for table data access.
func NewApiLogSetDao() *ApiLogSetDao {
	return &ApiLogSetDao{
		group:   "default",
		table:   "yjs_api_log_set",
		columns: apiLogSetColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ApiLogSetDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ApiLogSetDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ApiLogSetDao) Columns() ApiLogSetColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ApiLogSetDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ApiLogSetDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ApiLogSetDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
