// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// GameSamplesDao is the data access object for table yjs_game_samples.
type GameSamplesDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns GameSamplesColumns // columns contains all the column names of Table for convenient usage.
}

// GameSamplesColumns defines and stores column names for table yjs_game_samples.
type GameSamplesColumns struct {
	Id        string //
	Name      string //
	Samples   string //
	CreatedAt string //
	UpdatedAt string //
}

//  gameSamplesColumns holds the columns for table yjs_game_samples.
var gameSamplesColumns = GameSamplesColumns{
	Id:        "id",
	Name:      "name",
	Samples:   "samples",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewGameSamplesDao creates and returns a new DAO object for table data access.
func NewGameSamplesDao() *GameSamplesDao {
	return &GameSamplesDao{
		group:   "default",
		table:   "yjs_game_samples",
		columns: gameSamplesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *GameSamplesDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *GameSamplesDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *GameSamplesDao) Columns() GameSamplesColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *GameSamplesDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *GameSamplesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *GameSamplesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
