// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// NodeProductTypeDao is the data access object for table yjs_node_product_type.
type NodeProductTypeDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns NodeProductTypeColumns // columns contains all the column names of Table for convenient usage.
}

// NodeProductTypeColumns defines and stores column names for table yjs_node_product_type.
type NodeProductTypeColumns struct {
	Id            string //
	NodeId        string // 节点id
	ProductTypeId string // 套餐类型  'product_type'    => [          '1'=>"基础版",          '2'=>"稳定版",          '3'=>"专业版",          '4'=>"高级版",          '5'=>"定制版",      ],
	CreatedAt     string //
	UpdatedAt     string //
}

//  nodeProductTypeColumns holds the columns for table yjs_node_product_type.
var nodeProductTypeColumns = NodeProductTypeColumns{
	Id:            "id",
	NodeId:        "node_id",
	ProductTypeId: "product_type_id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

// NewNodeProductTypeDao creates and returns a new DAO object for table data access.
func NewNodeProductTypeDao() *NodeProductTypeDao {
	return &NodeProductTypeDao{
		group:   "default",
		table:   "yjs_node_product_type",
		columns: nodeProductTypeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *NodeProductTypeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *NodeProductTypeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *NodeProductTypeDao) Columns() NodeProductTypeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *NodeProductTypeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *NodeProductTypeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *NodeProductTypeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
