// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// NodesUserSerialDao is the data access object for table yjs_nodes_user_serial.
type NodesUserSerialDao struct {
	table   string                 // table is the underlying table name of the DAO.
	group   string                 // group is the database configuration group name of current DAO.
	columns NodesUserSerialColumns // columns contains all the column names of Table for convenient usage.
}

// NodesUserSerialColumns defines and stores column names for table yjs_nodes_user_serial.
type NodesUserSerialColumns struct {
	Id               string //
	NodeId           string // 节点id
	MachineId        string // 机房id
	UserSerialId     string // 用户产品id
	DistributionType string // 1手动分配，2自动分配
	Type             string // 1共享。2 独立
	NodeType         string // 1防御网关。2 安全网关
	CreatedAt        string //
	UpdatedAt        string //
}

//  nodesUserSerialColumns holds the columns for table yjs_nodes_user_serial.
var nodesUserSerialColumns = NodesUserSerialColumns{
	Id:               "id",
	NodeId:           "node_id",
	MachineId:        "machine_id",
	UserSerialId:     "user_serial_id",
	DistributionType: "distribution_type",
	Type:             "type",
	NodeType:         "node_type",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

// NewNodesUserSerialDao creates and returns a new DAO object for table data access.
func NewNodesUserSerialDao() *NodesUserSerialDao {
	return &NodesUserSerialDao{
		group:   "default",
		table:   "yjs_nodes_user_serial",
		columns: nodesUserSerialColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *NodesUserSerialDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *NodesUserSerialDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *NodesUserSerialDao) Columns() NodesUserSerialColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *NodesUserSerialDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *NodesUserSerialDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *NodesUserSerialDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
