// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// NodesIpDao is the data access object for table yjs_nodes_ip.
type NodesIpDao struct {
	table   string         // table is the underlying table name of the DAO.
	group   string         // group is the database configuration group name of current DAO.
	columns NodesIpColumns // columns contains all the column names of Table for convenient usage.
}

// NodesIpColumns defines and stores column names for table yjs_nodes_ip.
type NodesIpColumns struct {
	Id        string //
	NodeId    string // 节点id
	Ip        string //
	Type      string // 1是主ip
	CreatedAt string //
	UpdatedAt string //
	AreaSafe  string // 地区配置-用于匹配安全网关
}

//  nodesIpColumns holds the columns for table yjs_nodes_ip.
var nodesIpColumns = NodesIpColumns{
	Id:        "id",
	NodeId:    "node_id",
	Ip:        "ip",
	Type:      "type",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
	AreaSafe:  "area_safe",
}

// NewNodesIpDao creates and returns a new DAO object for table data access.
func NewNodesIpDao() *NodesIpDao {
	return &NodesIpDao{
		group:   "default",
		table:   "yjs_nodes_ip",
		columns: nodesIpColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *NodesIpDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *NodesIpDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *NodesIpDao) Columns() NodesIpColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *NodesIpDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *NodesIpDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *NodesIpDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
