// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// NodesUserProductDao is the data access object for table yjs_nodes_user_product.
type NodesUserProductDao struct {
	table   string                  // table is the underlying table name of the DAO.
	group   string                  // group is the database configuration group name of current DAO.
	columns NodesUserProductColumns // columns contains all the column names of Table for convenient usage.
}

// NodesUserProductColumns defines and stores column names for table yjs_nodes_user_product.
type NodesUserProductColumns struct {
	Id               string //
	NodeId           string // 节点id
	Ip               string // 对应的ip信息
	UserProductId    string // 用户产品id
	DistributionType string // 1手动分配，2自动分配
	Type             string // 1共享。2 独立
	NodeType         string // 1防御网关。2 安全网关
	CreatedAt        string //
	UpdatedAt        string //
}

//  nodesUserProductColumns holds the columns for table yjs_nodes_user_product.
var nodesUserProductColumns = NodesUserProductColumns{
	Id:               "id",
	NodeId:           "node_id",
	Ip:               "ip",
	UserProductId:    "user_product_id",
	DistributionType: "distribution_type",
	Type:             "type",
	NodeType:         "node_type",
	CreatedAt:        "created_at",
	UpdatedAt:        "updated_at",
}

// NewNodesUserProductDao creates and returns a new DAO object for table data access.
func NewNodesUserProductDao() *NodesUserProductDao {
	return &NodesUserProductDao{
		group:   "default",
		table:   "yjs_nodes_user_product",
		columns: nodesUserProductColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *NodesUserProductDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *NodesUserProductDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *NodesUserProductDao) Columns() NodesUserProductColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *NodesUserProductDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *NodesUserProductDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *NodesUserProductDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
