// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// NodesProvinceDao is the data access object for table yjs_nodes_province.
type NodesProvinceDao struct {
	table   string               // table is the underlying table name of the DAO.
	group   string               // group is the database configuration group name of current DAO.
	columns NodesProvinceColumns // columns contains all the column names of Table for convenient usage.
}

// NodesProvinceColumns defines and stores column names for table yjs_nodes_province.
type NodesProvinceColumns struct {
	Id           string //
	NodeId       string // 节点id
	ProvinceType string // 1、省级配置，2、市级配置
	Line         string // 线路1电信2联通3移动
	Area         string // 地区配置信息
	SerialList   string // 序列号列表
	SetType      string // 1允许 2限制
	CreatedAt    string //
	UpdatedAt    string //
}

//  nodesProvinceColumns holds the columns for table yjs_nodes_province.
var nodesProvinceColumns = NodesProvinceColumns{
	Id:           "id",
	NodeId:       "node_id",
	ProvinceType: "province_type",
	Line:         "line",
	Area:         "area",
	SerialList:   "serial_list",
	SetType:      "set_type",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

// NewNodesProvinceDao creates and returns a new DAO object for table data access.
func NewNodesProvinceDao() *NodesProvinceDao {
	return &NodesProvinceDao{
		group:   "default",
		table:   "yjs_nodes_province",
		columns: nodesProvinceColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *NodesProvinceDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *NodesProvinceDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *NodesProvinceDao) Columns() NodesProvinceColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *NodesProvinceDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *NodesProvinceDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *NodesProvinceDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
