// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// NoticetUserDao is the data access object for table yjs_noticet_user.
type NoticetUserDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns NoticetUserColumns // columns contains all the column names of Table for convenient usage.
}

// NoticetUserColumns defines and stores column names for table yjs_noticet_user.
type NoticetUserColumns struct {
	Id        string //
	UserId    string // 用户id
	NoticetId string // 公告id
	CreatedAt string //
	UpdatedAt string //
}

//  noticetUserColumns holds the columns for table yjs_noticet_user.
var noticetUserColumns = NoticetUserColumns{
	Id:        "id",
	UserId:    "user_id",
	NoticetId: "noticet_id",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewNoticetUserDao creates and returns a new DAO object for table data access.
func NewNoticetUserDao() *NoticetUserDao {
	return &NoticetUserDao{
		group:   "default",
		table:   "yjs_noticet_user",
		columns: noticetUserColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *NoticetUserDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *NoticetUserDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *NoticetUserDao) Columns() NoticetUserColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *NoticetUserDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *NoticetUserDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *NoticetUserDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
