// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// PreferentialStrategy1Dao is the data access object for table yjs_preferential_strategy1.
type PreferentialStrategy1Dao struct {
	table   string                       // table is the underlying table name of the DAO.
	group   string                       // group is the database configuration group name of current DAO.
	columns PreferentialStrategy1Columns // columns contains all the column names of Table for convenient usage.
}

// PreferentialStrategy1Columns defines and stores column names for table yjs_preferential_strategy1.
type PreferentialStrategy1Columns struct {
	Id                string //
	Type              string // 类型 1 购买 2 续费
	Operator          string // 操作人
	PreferentialHalf  string // 半年折扣
	PreferentialOne   string // 一年折扣
	PreferentialTwo   string // 两年折扣
	PreferentialThree string // 三年折扣
	CreatedAt         string //
	UpdatedAt         string //
}

//  preferentialStrategy1Columns holds the columns for table yjs_preferential_strategy1.
var preferentialStrategy1Columns = PreferentialStrategy1Columns{
	Id:                "id",
	Type:              "type",
	Operator:          "operator",
	PreferentialHalf:  "preferential_half",
	PreferentialOne:   "preferential_one",
	PreferentialTwo:   "preferential_two",
	PreferentialThree: "preferential_three",
	CreatedAt:         "created_at",
	UpdatedAt:         "updated_at",
}

// NewPreferentialStrategy1Dao creates and returns a new DAO object for table data access.
func NewPreferentialStrategy1Dao() *PreferentialStrategy1Dao {
	return &PreferentialStrategy1Dao{
		group:   "default",
		table:   "yjs_preferential_strategy1",
		columns: preferentialStrategy1Columns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *PreferentialStrategy1Dao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *PreferentialStrategy1Dao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *PreferentialStrategy1Dao) Columns() PreferentialStrategy1Columns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *PreferentialStrategy1Dao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *PreferentialStrategy1Dao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *PreferentialStrategy1Dao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
