// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ProvinceDao is the data access object for table yjs_province.
type ProvinceDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns ProvinceColumns // columns contains all the column names of Table for convenient usage.
}

// ProvinceColumns defines and stores column names for table yjs_province.
type ProvinceColumns struct {
	Id           string // 主键自增
	Pid          string // 父类id
	DistrictName string // 城市的名字
	Type         string // 城市的类型，0是国，1是省，2是市，3是区
	Hierarchy    string // 地区所处的层级
	DistrictSqe  string // 层级序列
	Partition    string // 分区，省有效 0其他 1东北 2华东 3华北 4华中 5华南 6西南 7西北
}

//  provinceColumns holds the columns for table yjs_province.
var provinceColumns = ProvinceColumns{
	Id:           "id",
	Pid:          "pid",
	DistrictName: "district_name",
	Type:         "type",
	Hierarchy:    "hierarchy",
	DistrictSqe:  "district_sqe",
	Partition:    "partition",
}

// NewProvinceDao creates and returns a new DAO object for table data access.
func NewProvinceDao() *ProvinceDao {
	return &ProvinceDao{
		group:   "default",
		table:   "yjs_province",
		columns: provinceColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ProvinceDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ProvinceDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ProvinceDao) Columns() ProvinceColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ProvinceDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ProvinceDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ProvinceDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
