// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SdkDao is the data access object for table yjs_sdk.
type SdkDao struct {
	table   string     // table is the underlying table name of the DAO.
	group   string     // group is the database configuration group name of current DAO.
	columns SdkColumns // columns contains all the column names of Table for convenient usage.
}

// SdkColumns defines and stores column names for table yjs_sdk.
type SdkColumns struct {
	Id        string //
	UserId    string // 用户id
	Number    string // 用户序列号
	Key       string // 秘钥
	Status    string // 1启用，2禁用
	Remark    string // 备注
	CreatedAt string //
	UpdatedAt string //
}

//  sdkColumns holds the columns for table yjs_sdk.
var sdkColumns = SdkColumns{
	Id:        "id",
	UserId:    "user_id",
	Number:    "number",
	Key:       "key",
	Status:    "status",
	Remark:    "remark",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewSdkDao creates and returns a new DAO object for table data access.
func NewSdkDao() *SdkDao {
	return &SdkDao{
		group:   "default",
		table:   "yjs_sdk",
		columns: sdkColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SdkDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SdkDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SdkDao) Columns() SdkColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SdkDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SdkDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SdkDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
