// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SerialReportCountIpDao is the data access object for table yjs_serial_report_count_ip.
type SerialReportCountIpDao struct {
	table   string                     // table is the underlying table name of the DAO.
	group   string                     // group is the database configuration group name of current DAO.
	columns SerialReportCountIpColumns // columns contains all the column names of Table for convenient usage.
}

// SerialReportCountIpColumns defines and stores column names for table yjs_serial_report_count_ip.
type SerialReportCountIpColumns struct {
	Id               string //
	ServerIp         string // ip
	CountUpLink      string //
	CountDownLink    string //
	CountConnections string //
	Status           string //
	CreatedAt        string //
}

//  serialReportCountIpColumns holds the columns for table yjs_serial_report_count_ip.
var serialReportCountIpColumns = SerialReportCountIpColumns{
	Id:               "id",
	ServerIp:         "server_ip",
	CountUpLink:      "count_up_link",
	CountDownLink:    "count_down_link",
	CountConnections: "count_connections",
	Status:           "status",
	CreatedAt:        "created_at",
}

// NewSerialReportCountIpDao creates and returns a new DAO object for table data access.
func NewSerialReportCountIpDao() *SerialReportCountIpDao {
	return &SerialReportCountIpDao{
		group:   "default",
		table:   "yjs_serial_report_count_ip",
		columns: serialReportCountIpColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SerialReportCountIpDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SerialReportCountIpDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SerialReportCountIpDao) Columns() SerialReportCountIpColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SerialReportCountIpDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SerialReportCountIpDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SerialReportCountIpDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
