// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// SerialReport202103Dao is the data access object for table yjs_serial_report_2021-03.
type SerialReport202103Dao struct {
	table   string                    // table is the underlying table name of the DAO.
	group   string                    // group is the database configuration group name of current DAO.
	columns SerialReport202103Columns // columns contains all the column names of Table for convenient usage.
}

// SerialReport202103Columns defines and stores column names for table yjs_serial_report_2021-03.
type SerialReport202103Columns struct {
	Id          string //
	Port        string //
	ProductNum  string //
	Connections string //
	UpLink      string //
	DownLink    string //
	ServerIp    string //
	CreatedAt   string //
	UpdatedAt   string //
}

//  serialReport202103Columns holds the columns for table yjs_serial_report_2021-03.
var serialReport202103Columns = SerialReport202103Columns{
	Id:          "id",
	Port:        "port",
	ProductNum:  "product_num",
	Connections: "connections",
	UpLink:      "up_link",
	DownLink:    "down_link",
	ServerIp:    "server_ip",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

// NewSerialReport202103Dao creates and returns a new DAO object for table data access.
func NewSerialReport202103Dao() *SerialReport202103Dao {
	return &SerialReport202103Dao{
		group:   "default",
		table:   "yjs_serial_report_2021-03",
		columns: serialReport202103Columns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *SerialReport202103Dao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *SerialReport202103Dao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *SerialReport202103Dao) Columns() SerialReport202103Columns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *SerialReport202103Dao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *SerialReport202103Dao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *SerialReport202103Dao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
