// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserProductConfigcommonDao is the data access object for table yjs_user_product_configcommon.
type UserProductConfigcommonDao struct {
	table   string                         // table is the underlying table name of the DAO.
	group   string                         // group is the database configuration group name of current DAO.
	columns UserProductConfigcommonColumns // columns contains all the column names of Table for convenient usage.
}

// UserProductConfigcommonColumns defines and stores column names for table yjs_user_product_configcommon.
type UserProductConfigcommonColumns struct {
	Id            string //
	Name          string // 配置名称
	UserProductId string //
	Lip           string // Local IP即终端代理要监听的本地Ip
	Port          string // 端口号
	Guid          string //
	CreatedAt     string //
	UpdatedAt     string //
}

//  userProductConfigcommonColumns holds the columns for table yjs_user_product_configcommon.
var userProductConfigcommonColumns = UserProductConfigcommonColumns{
	Id:            "id",
	Name:          "name",
	UserProductId: "user_product_id",
	Lip:           "lip",
	Port:          "port",
	Guid:          "guid",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
}

// NewUserProductConfigcommonDao creates and returns a new DAO object for table data access.
func NewUserProductConfigcommonDao() *UserProductConfigcommonDao {
	return &UserProductConfigcommonDao{
		group:   "default",
		table:   "yjs_user_product_configcommon",
		columns: userProductConfigcommonColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserProductConfigcommonDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserProductConfigcommonDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserProductConfigcommonDao) Columns() UserProductConfigcommonColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserProductConfigcommonDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserProductConfigcommonDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserProductConfigcommonDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
