// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserProductDao is the data access object for table yjs_user_product.
type UserProductDao struct {
	table   string             // table is the underlying table name of the DAO.
	group   string             // group is the database configuration group name of current DAO.
	columns UserProductColumns // columns contains all the column names of Table for convenient usage.
}

// UserProductColumns defines and stores column names for table yjs_user_product.
type UserProductColumns struct {
	Id                  string //
	UserId              string // 用户id
	ProductId           string // 产品id
	UserSerialId        string // 用户序列号表id
	ProductType         string // 对应产品表的类型
	HostName            string // 1是服务器2是云 应该没用了
	HostType            string // 1是服务器2是云 应该没用了
	HostId              string // 产品id 应该没用了
	OnOff               string // -1是未初始化，1是启用，2是关闭
	Status              string // 用户产品状态1正常 2关闭 -1未支付
	Name                string // 产品名称
	AvailablePoints     string // 可用点数
	AvaliableFrequency  string // 可用封装次数
	CreatedAt           string //
	UpdatedAt           string //
	StartAt             string // 生效日期
	EndAt               string // 失效日期
	Bz                  string // 客户那边的备注
	ClientLimit         string // 客户端最大连接数
	SharedNodesNum      string // 共享节点数 暂时没用
	IndependentNodesNum string // 独立节点数 暂时没用
	CountUpLink         string // 统计数据 没用了，改成中间表
	CountDownLink       string // 统计数据  没用了，改成中间表
	CountConnections    string // 统计数据 没用了，改成中间表
	CountAt             string // 统计数据时间 没用了，改成中间表
	IsLogo              string // 是否展示logo,1展示，0不展示
	Username            string // sdk字段-所属用户
	ProductNum          string // sdk字段-产品编号
	Amount              string // sdk字段-金额
	TradedMode          string // sdk字段-交易方式
	TradedType          string // sdk字段-交易类型
	OrderType           string // sdk字段-订单类型
	DeletedAt           string //
	Operator            string // SDK字段
	SourceType          string // 客户来源 1云加速 2sdk
	SdkNum              string // sdk_num
	Guid                string // 规则改变标识
	SkinFile            string // 客户端皮肤资源包 文件ID
	IcoImg              string // 托盘图标 文件ID
	Remarks             string // 数据中心-列表备注
	RealAmount          string // 数据中心-实际支付价格
	SellId              string // 销售id
	NodeLimit           string // 节点下发数量限制 后台配置
	AllRunningTime      string // 总包-运行时间
	AllAllowPackage     string // 总包-允许的总包数量
	AllShieldTime       string // 总包-屏蔽时间
	BigRunningTime      string // 大包-运行时间
	BigAllowPackage     string // 大包-允许的大包数量
	BigShieldTime       string // 大包-屏蔽时间
	PackageStatus       string // 包-开关
	RunningTime         string // 运行时间
	MaxConnect          string // 一定时间内最大连接数
	ShieldTime          string // 屏蔽时间
	ClientLimitStatus   string // 客户端最大连接数开关
	YjsLimitStatus      string // 云加速连接数开关
	YjsSdkLimitStatus   string // 云加速SDK连接数开关
	OperationName       string // 删除操作人
	DeleteRemark        string // 删除理由
	AutoRenew           string // 自动续费 0->关 1->开
	FlowStatus          string // 流量开关，1开，2关
	SamplesType         string // 样本类型
	DailyStatus         string // 日活开关，1开，2关
	SamplesTypeStatus   string // 样本类型开关 2手动维护
	SourceNum           string // 源机数量
}

//  userProductColumns holds the columns for table yjs_user_product.
var userProductColumns = UserProductColumns{
	Id:                  "id",
	UserId:              "user_id",
	ProductId:           "product_id",
	UserSerialId:        "user_serial_id",
	ProductType:         "product_type",
	HostName:            "host_name",
	HostType:            "host_type",
	HostId:              "host_id",
	OnOff:               "on_off",
	Status:              "status",
	Name:                "name",
	AvailablePoints:     "available_points",
	AvaliableFrequency:  "avaliable_frequency",
	CreatedAt:           "created_at",
	UpdatedAt:           "updated_at",
	StartAt:             "start_at",
	EndAt:               "end_at",
	Bz:                  "bz",
	ClientLimit:         "client_limit",
	SharedNodesNum:      "shared_nodes_num",
	IndependentNodesNum: "independent_nodes_num",
	CountUpLink:         "count_up_link",
	CountDownLink:       "count_down_link",
	CountConnections:    "count_connections",
	CountAt:             "count_at",
	IsLogo:              "is_logo",
	Username:            "username",
	ProductNum:          "product_num",
	Amount:              "amount",
	TradedMode:          "traded_mode",
	TradedType:          "traded_type",
	OrderType:           "order_type",
	DeletedAt:           "deleted_at",
	Operator:            "operator",
	SourceType:          "source_type",
	SdkNum:              "sdk_num",
	Guid:                "guid",
	SkinFile:            "skin_file",
	IcoImg:              "ico_img",
	Remarks:             "remarks",
	RealAmount:          "real_amount",
	SellId:              "sell_id",
	NodeLimit:           "node_limit",
	AllRunningTime:      "all_running_time",
	AllAllowPackage:     "all_allow_package",
	AllShieldTime:       "all_shield_time",
	BigRunningTime:      "big_running_time",
	BigAllowPackage:     "big_allow_package",
	BigShieldTime:       "big_shield_time",
	PackageStatus:       "package_status",
	RunningTime:         "running_time",
	MaxConnect:          "max_connect",
	ShieldTime:          "shield_time",
	ClientLimitStatus:   "client_limit_status",
	YjsLimitStatus:      "yjs_limit_status",
	YjsSdkLimitStatus:   "yjs_sdk_limit_status",
	OperationName:       "operation_name",
	DeleteRemark:        "delete_remark",
	AutoRenew:           "auto_renew",
	FlowStatus:          "flow_status",
	SamplesType:         "samples_type",
	DailyStatus:         "daily_status",
	SamplesTypeStatus:   "samples_type_status",
	SourceNum:           "source_num",
}

// NewUserProductDao creates and returns a new DAO object for table data access.
func NewUserProductDao() *UserProductDao {
	return &UserProductDao{
		group:   "default",
		table:   "yjs_user_product",
		columns: userProductColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserProductDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserProductDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserProductDao) Columns() UserProductColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserProductDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserProductDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserProductDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
