// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-06-06 15:21:14
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// UserNoticeDao is the data access object for table yjs_user_notice.
type UserNoticeDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns UserNoticeColumns // columns contains all the column names of Table for convenient usage.
}

// UserNoticeColumns defines and stores column names for table yjs_user_notice.
type UserNoticeColumns struct {
	Id        string // 记录ID
	UserId    string // 消息收件人
	Content   string // 消息内容
	State     string // 状态:1为已读,2为未读,默认为2
	CreatedAt string //
	UpdatedAt string //
}

//  userNoticeColumns holds the columns for table yjs_user_notice.
var userNoticeColumns = UserNoticeColumns{
	Id:        "id",
	UserId:    "user_id",
	Content:   "content",
	State:     "state",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

// NewUserNoticeDao creates and returns a new DAO object for table data access.
func NewUserNoticeDao() *UserNoticeDao {
	return &UserNoticeDao{
		group:   "default",
		table:   "yjs_user_notice",
		columns: userNoticeColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserNoticeDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *UserNoticeDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *UserNoticeDao) Columns() UserNoticeColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *UserNoticeDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserNoticeDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserNoticeDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
